2020-09-18T17:59:45: internal/fs.js:55
2020-09-18T17:59:45:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T17:59:45:   ^
2020-09-18T17:59:45: 
2020-09-18T17:59:45: Error: Unknown file open flag: undefined
2020-09-18T17:59:45:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T17:59:45:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T17:59:45:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T17:59:45:     at Module._compile (module.js:652:30)
2020-09-18T17:59:45:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T17:59:45:     at Module.load (module.js:565:32)
2020-09-18T17:59:45:     at tryModuleLoad (module.js:505:12)
2020-09-18T17:59:45:     at Function.Module._load (module.js:497:3)
2020-09-18T17:59:45:     at Function.Module.runMain (module.js:693:10)
2020-09-18T17:59:45:     at startup (bootstrap_node.js:188:16)
2020-09-18T17:59:45: npm
2020-09-18T17:59:45:  ERR! code ELIFECYCLE
2020-09-18T17:59:45: npm
2020-09-18T17:59:45:  ERR! errno 1
2020-09-18T17:59:45: npm
2020-09-18T17:59:45:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T17:59:45: npm ERR! Exit status 1
2020-09-18T17:59:45: npm
2020-09-18T17:59:45:  ERR! 
2020-09-18T17:59:45:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T17:59:45:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T17:59:47: 
2020-09-18T17:59:47: npm ERR! A complete log of this run can be found in:
2020-09-18T17:59:47: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T09_59_45_499Z-debug.log
2020-09-18T17:59:51: internal/fs.js:55
2020-09-18T17:59:51:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T17:59:51:   ^
2020-09-18T17:59:51: 
2020-09-18T17:59:51: Error: Unknown file open flag: undefined
2020-09-18T17:59:51:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T17:59:51:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T17:59:51:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T17:59:51:     at Module._compile (module.js:652:30)
2020-09-18T17:59:51:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T17:59:51:     at Module.load (module.js:565:32)
2020-09-18T17:59:51:     at tryModuleLoad (module.js:505:12)
2020-09-18T17:59:51:     at Function.Module._load (module.js:497:3)
2020-09-18T17:59:51:     at Function.Module.runMain (module.js:693:10)
2020-09-18T17:59:51:     at startup (bootstrap_node.js:188:16)
2020-09-18T17:59:51: npm
2020-09-18T17:59:51:  ERR! code ELIFECYCLE
2020-09-18T17:59:51: npm ERR! errno 1
2020-09-18T17:59:51: npm
2020-09-18T17:59:51:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T17:59:51: npm ERR! Exit status 1
2020-09-18T17:59:51:  ERR! 
2020-09-18T17:59:51: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T17:59:51: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T17:59:52: 
2020-09-18T17:59:52: npm ERR! A complete log of this run can be found in:
2020-09-18T17:59:52:  ERR!     /home/volumio/.npm/_logs/2020-09-18T09_59_51_491Z-debug.log
2020-09-18T17:59:56: internal/fs.js:55
2020-09-18T17:59:56:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T17:59:56:   ^
2020-09-18T17:59:56: 
2020-09-18T17:59:56: Error: Unknown file open flag: undefined
2020-09-18T17:59:56:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T17:59:56:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T17:59:56:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T17:59:56:     at Module._compile (module.js:652:30)
2020-09-18T17:59:56:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T17:59:56:     at Module.load (module.js:565:32)
2020-09-18T17:59:56:     at tryModuleLoad (module.js:505:12)
2020-09-18T17:59:56:     at Function.Module._load (module.js:497:3)
2020-09-18T17:59:56:     at Function.Module.runMain (module.js:693:10)
2020-09-18T17:59:56:     at startup (bootstrap_node.js:188:16)
2020-09-18T17:59:56: npm
2020-09-18T17:59:56:  ERR! code ELIFECYCLE
2020-09-18T17:59:56: npm ERR! errno 1
2020-09-18T17:59:56: npm
2020-09-18T17:59:56:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T17:59:56: npm ERR! Exit status 1
2020-09-18T17:59:56: npm ERR! 
2020-09-18T17:59:56: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T17:59:56:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T17:59:59: 
2020-09-18T17:59:59: npm ERR! A complete log of this run can be found in:
2020-09-18T17:59:59: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T09_59_56_469Z-debug.log
2020-09-18T18:00:04: internal/fs.js:55
2020-09-18T18:00:04:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:04:   ^
2020-09-18T18:00:04: 
2020-09-18T18:00:04: Error: Unknown file open flag: undefined
2020-09-18T18:00:04:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:04:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:04:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:04:     at Module._compile (module.js:652:30)
2020-09-18T18:00:04:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:04:     at Module.load (module.js:565:32)
2020-09-18T18:00:04:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:04:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:04:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:04:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:04: npm
2020-09-18T18:00:04:  
2020-09-18T18:00:04: ERR!
2020-09-18T18:00:04:  
2020-09-18T18:00:04: code
2020-09-18T18:00:04:  ELIFECYCLE
2020-09-18T18:00:04: npm ERR! errno 1
2020-09-18T18:00:04: npm
2020-09-18T18:00:04:  
2020-09-18T18:00:04: ERR!
2020-09-18T18:00:04:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:04: npm
2020-09-18T18:00:04:  ERR! Exit status 1
2020-09-18T18:00:04: npm ERR! 
2020-09-18T18:00:04: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:04:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:06: 
2020-09-18T18:00:06: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:06: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_04_091Z-debug.log
2020-09-18T18:00:11: internal/fs.js:55
2020-09-18T18:00:11:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:11:   ^
2020-09-18T18:00:11: 
2020-09-18T18:00:11: Error: Unknown file open flag: undefined
2020-09-18T18:00:11:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:11:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:11:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:11:     at Module._compile (module.js:652:30)
2020-09-18T18:00:11:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:11:     at Module.load (module.js:565:32)
2020-09-18T18:00:11:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:11:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:11:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:11:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:11: npm
2020-09-18T18:00:11:  ERR! code ELIFECYCLE
2020-09-18T18:00:11: npm ERR! errno 1
2020-09-18T18:00:11: npm
2020-09-18T18:00:11:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:11: npm ERR! Exit status 1
2020-09-18T18:00:11: npm ERR! 
2020-09-18T18:00:11: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:11: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:13: 
2020-09-18T18:00:13: npm
2020-09-18T18:00:13:  ERR! A complete log of this run can be found in:
2020-09-18T18:00:13: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_11_167Z-debug.log
2020-09-18T18:00:18: internal/fs.js:55
2020-09-18T18:00:18:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:18:   ^
2020-09-18T18:00:18: 
2020-09-18T18:00:18: Error: Unknown file open flag: undefined
2020-09-18T18:00:18:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:18:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:18:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:18:     at Module._compile (module.js:652:30)
2020-09-18T18:00:18:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:18:     at Module.load (module.js:565:32)
2020-09-18T18:00:18:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:18:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:18:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:18:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:18: npm
2020-09-18T18:00:18:  
2020-09-18T18:00:18: ERR!
2020-09-18T18:00:18:  
2020-09-18T18:00:18: code
2020-09-18T18:00:18:  ELIFECYCLE
2020-09-18T18:00:18: npm ERR! errno 1
2020-09-18T18:00:18: npm
2020-09-18T18:00:18:  
2020-09-18T18:00:18: ERR!
2020-09-18T18:00:18:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:18: npm
2020-09-18T18:00:18:  ERR! Exit status 1
2020-09-18T18:00:18: npm ERR! 
2020-09-18T18:00:18: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:18: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:20: 
2020-09-18T18:00:20: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:20: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_18_123Z-debug.log
2020-09-18T18:00:25: internal/fs.js:55
2020-09-18T18:00:25:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:25:   ^
2020-09-18T18:00:25: 
2020-09-18T18:00:25: Error: Unknown file open flag: undefined
2020-09-18T18:00:25:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:25:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:25:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:25:     at Module._compile (module.js:652:30)
2020-09-18T18:00:25:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:25:     at Module.load (module.js:565:32)
2020-09-18T18:00:25:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:25:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:25:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:25:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:25: npm
2020-09-18T18:00:25:  
2020-09-18T18:00:25: ERR!
2020-09-18T18:00:25:  
2020-09-18T18:00:25: code
2020-09-18T18:00:25:  ELIFECYCLE
2020-09-18T18:00:25: npm ERR! errno 1
2020-09-18T18:00:25: npm
2020-09-18T18:00:25:  
2020-09-18T18:00:25: ERR!
2020-09-18T18:00:25:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:25: npm ERR! Exit status 1
2020-09-18T18:00:25: npm ERR! 
2020-09-18T18:00:25:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:25: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:27: 
2020-09-18T18:00:27: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:27: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_25_386Z-debug.log
2020-09-18T18:00:32: internal/fs.js:55
2020-09-18T18:00:32:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:32:   ^
2020-09-18T18:00:32: 
2020-09-18T18:00:32: Error: Unknown file open flag: undefined
2020-09-18T18:00:32:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:32:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:32:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:32:     at Module._compile (module.js:652:30)
2020-09-18T18:00:32:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:32:     at Module.load (module.js:565:32)
2020-09-18T18:00:32:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:32:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:32:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:32:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:32: npm
2020-09-18T18:00:32:  ERR! code ELIFECYCLE
2020-09-18T18:00:32: npm 
2020-09-18T18:00:32: ERR! errno 1
2020-09-18T18:00:32: npm
2020-09-18T18:00:32:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:32: npm ERR! Exit status 1
2020-09-18T18:00:32: npm ERR! 
2020-09-18T18:00:32: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:32: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:34: 
2020-09-18T18:00:34: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:34: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_32_577Z-debug.log
2020-09-18T18:00:39: internal/fs.js:55
2020-09-18T18:00:39:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:39:   ^
2020-09-18T18:00:39: 
2020-09-18T18:00:39: Error: Unknown file open flag: undefined
2020-09-18T18:00:39:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:39:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:39:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:39:     at Module._compile (module.js:652:30)
2020-09-18T18:00:39:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:39:     at Module.load (module.js:565:32)
2020-09-18T18:00:39:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:39:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:39:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:39:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:39: npm ERR! code ELIFECYCLE
2020-09-18T18:00:39: npm ERR! errno 1
2020-09-18T18:00:39: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:39: npm ERR! Exit status 1
2020-09-18T18:00:39:  ERR! 
2020-09-18T18:00:39: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:39: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:41: 
2020-09-18T18:00:41: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:41: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_39_937Z-debug.log
2020-09-18T18:00:47: internal/fs.js:55
2020-09-18T18:00:47:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:47:   ^
2020-09-18T18:00:47: 
2020-09-18T18:00:47: Error: Unknown file open flag: undefined
2020-09-18T18:00:47:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:47:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:47:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:47:     at Module._compile (module.js:652:30)
2020-09-18T18:00:47:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:47:     at Module.load (module.js:565:32)
2020-09-18T18:00:47:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:47:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:47:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:47:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:47: npm ERR! code ELIFECYCLE
2020-09-18T18:00:47: npm ERR! errno 1
2020-09-18T18:00:47: npm
2020-09-18T18:00:47:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:47: npm ERR! Exit status 1
2020-09-18T18:00:47: npm ERR! 
2020-09-18T18:00:47: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:47: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:49: 
2020-09-18T18:00:49: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:49: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_47_066Z-debug.log
2020-09-18T18:00:54: internal/fs.js:55
2020-09-18T18:00:54:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:00:54:   ^
2020-09-18T18:00:54: 
2020-09-18T18:00:54: Error: Unknown file open flag: undefined
2020-09-18T18:00:54:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:00:54:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:00:54:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:00:54:     at Module._compile (module.js:652:30)
2020-09-18T18:00:54:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:00:54:     at Module.load (module.js:565:32)
2020-09-18T18:00:54:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:00:54:     at Function.Module._load (module.js:497:3)
2020-09-18T18:00:54:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:00:54:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:00:54: npm
2020-09-18T18:00:54:  ERR! code ELIFECYCLE
2020-09-18T18:00:54: npm ERR! errno 1
2020-09-18T18:00:54: npm
2020-09-18T18:00:54:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:00:54: npm ERR! Exit status 1
2020-09-18T18:00:54: npm ERR! 
2020-09-18T18:00:54: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:00:54: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:00:56: 
2020-09-18T18:00:56: npm ERR! A complete log of this run can be found in:
2020-09-18T18:00:56: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_00_54_426Z-debug.log
2020-09-18T18:01:01: internal/fs.js:55
2020-09-18T18:01:01:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:01:   ^
2020-09-18T18:01:01: 
2020-09-18T18:01:01: Error: Unknown file open flag: undefined
2020-09-18T18:01:01:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:01:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:01:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:01:     at Module._compile (module.js:652:30)
2020-09-18T18:01:01:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:01:     at Module.load (module.js:565:32)
2020-09-18T18:01:01:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:01:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:01:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:01:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:01: npm
2020-09-18T18:01:01:  ERR! code ELIFECYCLE
2020-09-18T18:01:01: npm ERR! errno 1
2020-09-18T18:01:01: npm
2020-09-18T18:01:01:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:01: npm ERR! Exit status 1
2020-09-18T18:01:01: npm ERR! 
2020-09-18T18:01:01: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:01:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:03: 
2020-09-18T18:01:03: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:03: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_01_550Z-debug.log
2020-09-18T18:01:08: internal/fs.js:55
2020-09-18T18:01:08:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:08:   ^
2020-09-18T18:01:08: 
2020-09-18T18:01:08: Error: Unknown file open flag: undefined
2020-09-18T18:01:08:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:08:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:08:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:08:     at Module._compile (module.js:652:30)
2020-09-18T18:01:08:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:08:     at Module.load (module.js:565:32)
2020-09-18T18:01:08:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:08:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:08:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:08:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:08: npm
2020-09-18T18:01:08:  
2020-09-18T18:01:08: ERR!
2020-09-18T18:01:08:  
2020-09-18T18:01:08: code ELIFECYCLE
2020-09-18T18:01:08: npm ERR! errno 1
2020-09-18T18:01:08: npm
2020-09-18T18:01:08:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:08: npm ERR! Exit status 1
2020-09-18T18:01:08: npm ERR! 
2020-09-18T18:01:08: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:08: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:10: 
2020-09-18T18:01:10: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:10: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_08_182Z-debug.log
2020-09-18T18:01:16: internal/fs.js:55
2020-09-18T18:01:16:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:16:   ^
2020-09-18T18:01:16: 
2020-09-18T18:01:16: Error: Unknown file open flag: undefined
2020-09-18T18:01:16:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:16:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:16:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:16:     at Module._compile (module.js:652:30)
2020-09-18T18:01:16:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:16:     at Module.load (module.js:565:32)
2020-09-18T18:01:16:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:16:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:16:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:16:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:16: npm
2020-09-18T18:01:16:  
2020-09-18T18:01:16: ERR!
2020-09-18T18:01:16:  code
2020-09-18T18:01:16:  ELIFECYCLE
2020-09-18T18:01:16: errno 1
2020-09-18T18:01:16: npm
2020-09-18T18:01:16:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:16: npm ERR! Exit status 1
2020-09-18T18:01:16: npm ERR! 
2020-09-18T18:01:16: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:16: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:18: 
2020-09-18T18:01:18: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:18: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_16_179Z-debug.log
2020-09-18T18:01:23: internal/fs.js:55
2020-09-18T18:01:23:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:23:   ^
2020-09-18T18:01:23: 
2020-09-18T18:01:23: Error: Unknown file open flag: undefined
2020-09-18T18:01:23:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:23:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:23:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:23:     at Module._compile (module.js:652:30)
2020-09-18T18:01:23:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:23:     at Module.load (module.js:565:32)
2020-09-18T18:01:23:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:23:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:23:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:23:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:23: npm
2020-09-18T18:01:23:  
2020-09-18T18:01:23: ERR! 
2020-09-18T18:01:23: code ELIFECYCLE
2020-09-18T18:01:23: ERR! errno 1
2020-09-18T18:01:23: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:23: npm ERR! Exit status 1
2020-09-18T18:01:23: npm ERR! 
2020-09-18T18:01:23: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:23: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:25: 
2020-09-18T18:01:25: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:25: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_23_453Z-debug.log
2020-09-18T18:01:30: internal/fs.js:55
2020-09-18T18:01:30:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:30:   ^
2020-09-18T18:01:30: 
2020-09-18T18:01:30: Error: Unknown file open flag: undefined
2020-09-18T18:01:30:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:30:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:30:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:30:     at Module._compile (module.js:652:30)
2020-09-18T18:01:30:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:30:     at Module.load (module.js:565:32)
2020-09-18T18:01:30:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:30:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:30:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:30:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:30: npm
2020-09-18T18:01:30:  ERR! code ELIFECYCLE
2020-09-18T18:01:30: npm ERR! errno 1
2020-09-18T18:01:30: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:30:  Exit status 1
2020-09-18T18:01:30: npm ERR! 
2020-09-18T18:01:30: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:30: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:32: 
2020-09-18T18:01:32: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:32: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_30_698Z-debug.log
2020-09-18T18:01:37: internal/fs.js:55
2020-09-18T18:01:37:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:37:   ^
2020-09-18T18:01:37: 
2020-09-18T18:01:37: Error: Unknown file open flag: undefined
2020-09-18T18:01:37:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:37:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:37:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:37:     at Module._compile (module.js:652:30)
2020-09-18T18:01:37:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:37:     at Module.load (module.js:565:32)
2020-09-18T18:01:37:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:37:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:37:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:37:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:37: npm
2020-09-18T18:01:37:  
2020-09-18T18:01:37: ERR!
2020-09-18T18:01:37:  
2020-09-18T18:01:37: code
2020-09-18T18:01:37:  ELIFECYCLE
2020-09-18T18:01:37: ERR! errno 1
2020-09-18T18:01:37: npm
2020-09-18T18:01:37:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:37: npm ERR! Exit status 1
2020-09-18T18:01:37: npm ERR! 
2020-09-18T18:01:37: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:37: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:39: 
2020-09-18T18:01:39: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:39: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_37_896Z-debug.log
2020-09-18T18:01:44: internal/fs.js:55
2020-09-18T18:01:44:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:44:   ^
2020-09-18T18:01:44: 
2020-09-18T18:01:44: Error: Unknown file open flag: undefined
2020-09-18T18:01:44:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:44:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:44:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:44:     at Module._compile (module.js:652:30)
2020-09-18T18:01:44:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:44:     at Module.load (module.js:565:32)
2020-09-18T18:01:44:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:44:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:44:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:44:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:44: npm
2020-09-18T18:01:44:  ERR! code ELIFECYCLE
2020-09-18T18:01:44: npm ERR! errno 1
2020-09-18T18:01:44: npm
2020-09-18T18:01:44:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:44: npm ERR! Exit status 1
2020-09-18T18:01:44: npm ERR! 
2020-09-18T18:01:44: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:44: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:47: 
2020-09-18T18:01:47: npm ERR! A complete log of this run can be found in:
2020-09-18T18:01:47: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_44_835Z-debug.log
2020-09-18T18:01:52: internal/fs.js:55
2020-09-18T18:01:52:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:52:   ^
2020-09-18T18:01:52: 
2020-09-18T18:01:52: Error: Unknown file open flag: undefined
2020-09-18T18:01:52:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:52:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:52:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:52:     at Module._compile (module.js:652:30)
2020-09-18T18:01:52:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:52:     at Module.load (module.js:565:32)
2020-09-18T18:01:52:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:52:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:52:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:52:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:52: npm
2020-09-18T18:01:52:  
2020-09-18T18:01:52: ERR! code ELIFECYCLE
2020-09-18T18:01:52: npm 
2020-09-18T18:01:52: ERR! errno 1
2020-09-18T18:01:52: npm
2020-09-18T18:01:52:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:52: npm ERR! Exit status 1
2020-09-18T18:01:52: npm ERR!
2020-09-18T18:01:52:  
2020-09-18T18:01:52: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:52: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:01:54: 
2020-09-18T18:01:54: npm
2020-09-18T18:01:54:  
2020-09-18T18:01:54: ERR!
2020-09-18T18:01:54:  A complete log of this run can be found in:
2020-09-18T18:01:54: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_52_214Z-debug.log
2020-09-18T18:01:58: internal/fs.js:55
2020-09-18T18:01:58:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:01:58:   ^
2020-09-18T18:01:58: 
2020-09-18T18:01:58: Error: Unknown file open flag: undefined
2020-09-18T18:01:58:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:01:58:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:01:58:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:01:58:     at Module._compile (module.js:652:30)
2020-09-18T18:01:58:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:01:58:     at Module.load (module.js:565:32)
2020-09-18T18:01:58:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:01:58:     at Function.Module._load (module.js:497:3)
2020-09-18T18:01:58:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:01:58:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:01:58: npm
2020-09-18T18:01:58:  ERR! code ELIFECYCLE
2020-09-18T18:01:58: npm ERR! errno 1
2020-09-18T18:01:59: npm
2020-09-18T18:01:59:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:01:59: npm ERR! Exit status 1
2020-09-18T18:01:59: npm ERR! 
2020-09-18T18:01:59: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:01:59: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:01: 
2020-09-18T18:02:01: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:01: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_01_59_011Z-debug.log
2020-09-18T18:02:06: internal/fs.js:55
2020-09-18T18:02:06:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:06:   ^
2020-09-18T18:02:06: 
2020-09-18T18:02:06: Error: Unknown file open flag: undefined
2020-09-18T18:02:06:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:06:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:06:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:06:     at Module._compile (module.js:652:30)
2020-09-18T18:02:06:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:06:     at Module.load (module.js:565:32)
2020-09-18T18:02:06:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:06:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:06:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:06:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:06: npm
2020-09-18T18:02:06:  ERR! code ELIFECYCLE
2020-09-18T18:02:06: npm
2020-09-18T18:02:06:  ERR! errno 1
2020-09-18T18:02:06: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:06: npm ERR! Exit status 1
2020-09-18T18:02:06: npm ERR! 
2020-09-18T18:02:06: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:06: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:08: 
2020-09-18T18:02:08: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:08: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_06_214Z-debug.log
2020-09-18T18:02:13: internal/fs.js:55
2020-09-18T18:02:13:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:13:   ^
2020-09-18T18:02:13: 
2020-09-18T18:02:13: Error: Unknown file open flag: undefined
2020-09-18T18:02:13:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:13:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:13:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:13:     at Module._compile (module.js:652:30)
2020-09-18T18:02:13:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:13:     at Module.load (module.js:565:32)
2020-09-18T18:02:13:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:13:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:13:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:13:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:13: npm
2020-09-18T18:02:13:  ERR! code ELIFECYCLE
2020-09-18T18:02:13: npm ERR! errno 1
2020-09-18T18:02:13: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:13: npm ERR! Exit status 1
2020-09-18T18:02:13: npm ERR! 
2020-09-18T18:02:13: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:13: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:15: 
2020-09-18T18:02:15: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:15:      /home/volumio/.npm/_logs/2020-09-18T10_02_13_834Z-debug.log
2020-09-18T18:02:20: internal/fs.js:55
2020-09-18T18:02:20:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:20:   ^
2020-09-18T18:02:20: 
2020-09-18T18:02:20: Error: Unknown file open flag: undefined
2020-09-18T18:02:20:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:20:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:20:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:20:     at Module._compile (module.js:652:30)
2020-09-18T18:02:20:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:20:     at Module.load (module.js:565:32)
2020-09-18T18:02:20:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:20:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:20:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:20:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:20: npm
2020-09-18T18:02:20:  ERR! code ELIFECYCLE
2020-09-18T18:02:20: npm ERR! errno 1
2020-09-18T18:02:20: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:20: npm ERR! Exit status 1
2020-09-18T18:02:20: npm ERR! 
2020-09-18T18:02:20: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:20: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:23: 
2020-09-18T18:02:23: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:23: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_20_149Z-debug.log
2020-09-18T18:02:27: internal/fs.js:55
2020-09-18T18:02:27:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:27:   ^
2020-09-18T18:02:27: 
2020-09-18T18:02:27: Error: Unknown file open flag: undefined
2020-09-18T18:02:27:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:27:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:27:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:27:     at Module._compile (module.js:652:30)
2020-09-18T18:02:27:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:27:     at Module.load (module.js:565:32)
2020-09-18T18:02:27:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:27:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:27:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:27:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:27: npm
2020-09-18T18:02:27:  ERR! code ELIFECYCLE
2020-09-18T18:02:27: npm ERR! errno 1
2020-09-18T18:02:27: npm
2020-09-18T18:02:27:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:27: npm ERR! Exit status 1
2020-09-18T18:02:27: npm ERR! 
2020-09-18T18:02:27: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:27: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:29: 
2020-09-18T18:02:29: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:29: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_27_551Z-debug.log
2020-09-18T18:02:34: internal/fs.js:55
2020-09-18T18:02:34:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:34:   ^
2020-09-18T18:02:34: 
2020-09-18T18:02:34: Error: Unknown file open flag: undefined
2020-09-18T18:02:34:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:34:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:34:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:34:     at Module._compile (module.js:652:30)
2020-09-18T18:02:34:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:34:     at Module.load (module.js:565:32)
2020-09-18T18:02:34:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:34:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:34:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:34:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:34: npm
2020-09-18T18:02:34:  ERR! code ELIFECYCLE
2020-09-18T18:02:34:  errno 1
2020-09-18T18:02:34: npm
2020-09-18T18:02:34:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:34: npm ERR! Exit status 1
2020-09-18T18:02:34: npm ERR! 
2020-09-18T18:02:34: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:34: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:36: 
2020-09-18T18:02:36: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:36: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_34_463Z-debug.log
2020-09-18T18:02:41: internal/fs.js:55
2020-09-18T18:02:41:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:41:   ^
2020-09-18T18:02:41: 
2020-09-18T18:02:41: Error: Unknown file open flag: undefined
2020-09-18T18:02:41:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:41:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:41:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:41:     at Module._compile (module.js:652:30)
2020-09-18T18:02:41:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:41:     at Module.load (module.js:565:32)
2020-09-18T18:02:41:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:41:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:41:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:41:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:41: npm
2020-09-18T18:02:41:  ERR! code ELIFECYCLE
2020-09-18T18:02:41: npm ERR! errno 1
2020-09-18T18:02:41: npm
2020-09-18T18:02:41:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:41: npm ERR! Exit status 1
2020-09-18T18:02:41: npm ERR! 
2020-09-18T18:02:41: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:41: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:44: 
2020-09-18T18:02:44: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:44: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_41_556Z-debug.log
2020-09-18T18:02:48: internal/fs.js:55
2020-09-18T18:02:48:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:48:   ^
2020-09-18T18:02:48: 
2020-09-18T18:02:48: Error: Unknown file open flag: undefined
2020-09-18T18:02:48:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:48:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:48:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:48:     at Module._compile (module.js:652:30)
2020-09-18T18:02:48:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:48:     at Module.load (module.js:565:32)
2020-09-18T18:02:48:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:48:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:48:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:48:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:48: npm
2020-09-18T18:02:48:  ERR! code ELIFECYCLE
2020-09-18T18:02:48: npm ERR! errno 1
2020-09-18T18:02:48: npm
2020-09-18T18:02:48:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:48: npm ERR! Exit status 1
2020-09-18T18:02:48: npm ERR! 
2020-09-18T18:02:48: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:48: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:51: 
2020-09-18T18:02:51: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:51: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_48_788Z-debug.log
2020-09-18T18:02:54: internal/fs.js:55
2020-09-18T18:02:54:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:54:   ^
2020-09-18T18:02:54: 
2020-09-18T18:02:54: Error: Unknown file open flag: undefined
2020-09-18T18:02:54:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:54:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:54:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:54:     at Module._compile (module.js:652:30)
2020-09-18T18:02:54:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:54:     at Module.load (module.js:565:32)
2020-09-18T18:02:54:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:54:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:54:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:54:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:54: npm
2020-09-18T18:02:54:  ERR! code ELIFECYCLE
2020-09-18T18:02:54: npm ERR! errno 1
2020-09-18T18:02:54: npm
2020-09-18T18:02:54:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:54: npm ERR! Exit status 1
2020-09-18T18:02:54: npm ERR! 
2020-09-18T18:02:54: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:54: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:02:55: 
2020-09-18T18:02:55: npm ERR! A complete log of this run can be found in:
2020-09-18T18:02:55: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_54_995Z-debug.log
2020-09-18T18:02:59: internal/fs.js:55
2020-09-18T18:02:59:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:02:59:   ^
2020-09-18T18:02:59: 
2020-09-18T18:02:59: Error: Unknown file open flag: undefined
2020-09-18T18:02:59:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:02:59:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:02:59:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:02:59:     at Module._compile (module.js:652:30)
2020-09-18T18:02:59:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:02:59:     at Module.load (module.js:565:32)
2020-09-18T18:02:59:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:02:59:     at Function.Module._load (module.js:497:3)
2020-09-18T18:02:59:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:02:59:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:02:59: npm
2020-09-18T18:02:59:  
2020-09-18T18:02:59: ERR!
2020-09-18T18:02:59:  code ELIFECYCLE
2020-09-18T18:02:59: ERR! errno 1
2020-09-18T18:02:59: npm
2020-09-18T18:02:59:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:02:59: npm ERR! Exit status 1
2020-09-18T18:02:59: npm ERR! 
2020-09-18T18:02:59: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:02:59: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:02: 
2020-09-18T18:03:02: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:02: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_02_59_860Z-debug.log
2020-09-18T18:03:06: internal/fs.js:55
2020-09-18T18:03:06:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:06:   ^
2020-09-18T18:03:06: 
2020-09-18T18:03:06: Error: Unknown file open flag: undefined
2020-09-18T18:03:06:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:06:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:06:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:06:     at Module._compile (module.js:652:30)
2020-09-18T18:03:06:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:06:     at Module.load (module.js:565:32)
2020-09-18T18:03:06:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:06:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:06:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:06:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:06: npm
2020-09-18T18:03:06:  ERR! code ELIFECYCLE
2020-09-18T18:03:06: npm 
2020-09-18T18:03:06: ERR! errno 1
2020-09-18T18:03:06: npm ERR!
2020-09-18T18:03:06:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:06: npm ERR! Exit status 1
2020-09-18T18:03:06:  
2020-09-18T18:03:06: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:06: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:09: 
2020-09-18T18:03:09: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:09: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_06_585Z-debug.log
2020-09-18T18:03:14: internal/fs.js:55
2020-09-18T18:03:14:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:14:   ^
2020-09-18T18:03:14: 
2020-09-18T18:03:14: Error: Unknown file open flag: undefined
2020-09-18T18:03:14:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:14:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:14:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:14:     at Module._compile (module.js:652:30)
2020-09-18T18:03:14:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:14:     at Module.load (module.js:565:32)
2020-09-18T18:03:14:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:14:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:14:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:14:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:14: npm
2020-09-18T18:03:14:  ERR! code
2020-09-18T18:03:14:  ELIFECYCLE
2020-09-18T18:03:14: npm
2020-09-18T18:03:14:  ERR! errno 1
2020-09-18T18:03:14: npm
2020-09-18T18:03:14:  
2020-09-18T18:03:14: ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:14: npm ERR! Exit status 1
2020-09-18T18:03:14: npm ERR! 
2020-09-18T18:03:14: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:14:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:16: 
2020-09-18T18:03:16: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:16: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_14_162Z-debug.log
2020-09-18T18:03:20: internal/fs.js:55
2020-09-18T18:03:20:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:20:   ^
2020-09-18T18:03:20: 
2020-09-18T18:03:20: Error: Unknown file open flag: undefined
2020-09-18T18:03:20:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:20:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:20:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:20:     at Module._compile (module.js:652:30)
2020-09-18T18:03:20:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:20:     at Module.load (module.js:565:32)
2020-09-18T18:03:20:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:20:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:20:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:20:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:20: npm
2020-09-18T18:03:20:  
2020-09-18T18:03:20: ERR!
2020-09-18T18:03:20:  
2020-09-18T18:03:20: code ELIFECYCLE
2020-09-18T18:03:20: npm ERR! errno 1
2020-09-18T18:03:20: npm
2020-09-18T18:03:20:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:20: npm ERR! Exit status 1
2020-09-18T18:03:20: npm ERR! 
2020-09-18T18:03:20:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:20: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:23: 
2020-09-18T18:03:23: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:23: ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_20_604Z-debug.log
2020-09-18T18:03:27: internal/fs.js:55
2020-09-18T18:03:27:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:27:   ^
2020-09-18T18:03:27: 
2020-09-18T18:03:27: Error: Unknown file open flag: undefined
2020-09-18T18:03:27:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:27:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:27:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:27:     at Module._compile (module.js:652:30)
2020-09-18T18:03:27:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:27:     at Module.load (module.js:565:32)
2020-09-18T18:03:27:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:27:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:27:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:27:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:27: npm
2020-09-18T18:03:27:  
2020-09-18T18:03:27: ERR! code ELIFECYCLE
2020-09-18T18:03:27:  ERR! errno 1
2020-09-18T18:03:27: npm
2020-09-18T18:03:27:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:27: npm ERR! Exit status 1
2020-09-18T18:03:27: npm ERR! 
2020-09-18T18:03:27: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:27:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:30: 
2020-09-18T18:03:30: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:30: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_27_829Z-debug.log
2020-09-18T18:03:34: internal/fs.js:55
2020-09-18T18:03:34:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:34:   ^
2020-09-18T18:03:34: 
2020-09-18T18:03:34: Error: Unknown file open flag: undefined
2020-09-18T18:03:34:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:34:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:34:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:34:     at Module._compile (module.js:652:30)
2020-09-18T18:03:34:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:34:     at Module.load (module.js:565:32)
2020-09-18T18:03:34:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:34:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:34:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:34:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:34: npm
2020-09-18T18:03:34:  ERR! 
2020-09-18T18:03:34: code ELIFECYCLE
2020-09-18T18:03:34:  ERR! errno 1
2020-09-18T18:03:34: npm
2020-09-18T18:03:34:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:34: npm ERR! Exit status 1
2020-09-18T18:03:34:  
2020-09-18T18:03:34: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:34: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:37: 
2020-09-18T18:03:37: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:37: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_34_703Z-debug.log
2020-09-18T18:03:42: internal/fs.js:55
2020-09-18T18:03:42:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:42:   ^
2020-09-18T18:03:42: 
2020-09-18T18:03:42: Error: Unknown file open flag: undefined
2020-09-18T18:03:42:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:42:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:42:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:42:     at Module._compile (module.js:652:30)
2020-09-18T18:03:42:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:42:     at Module.load (module.js:565:32)
2020-09-18T18:03:42:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:42:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:42:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:42:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:42: npm
2020-09-18T18:03:42:  
2020-09-18T18:03:42: ERR! code ELIFECYCLE
2020-09-18T18:03:42: ERR! errno 1
2020-09-18T18:03:42: npm
2020-09-18T18:03:42:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:42: npm ERR! Exit status 1
2020-09-18T18:03:42: npm ERR! 
2020-09-18T18:03:42:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:42: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:44: 
2020-09-18T18:03:44: npm 
2020-09-18T18:03:44: ERR! A complete log of this run can be found in:
2020-09-18T18:03:44: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_42_243Z-debug.log
2020-09-18T18:03:49: internal/fs.js:55
2020-09-18T18:03:49:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:49:   ^
2020-09-18T18:03:49: 
2020-09-18T18:03:49: Error: Unknown file open flag: undefined
2020-09-18T18:03:49:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:49:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:49:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:49:     at Module._compile (module.js:652:30)
2020-09-18T18:03:49:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:49:     at Module.load (module.js:565:32)
2020-09-18T18:03:49:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:49:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:49:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:49:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:49: npm
2020-09-18T18:03:49:  ERR! code ELIFECYCLE
2020-09-18T18:03:49: npm ERR! errno 1
2020-09-18T18:03:49: npm
2020-09-18T18:03:49:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:49: npm ERR! Exit status 1
2020-09-18T18:03:49: npm ERR! 
2020-09-18T18:03:49: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:49:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:51: 
2020-09-18T18:03:51: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:51: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_49_460Z-debug.log
2020-09-18T18:03:56: internal/fs.js:55
2020-09-18T18:03:56:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:03:56:   ^
2020-09-18T18:03:56: 
2020-09-18T18:03:56: Error: Unknown file open flag: undefined
2020-09-18T18:03:56:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:03:56:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:03:56:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:03:56:     at Module._compile (module.js:652:30)
2020-09-18T18:03:56:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:03:56:     at Module.load (module.js:565:32)
2020-09-18T18:03:56:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:03:56:     at Function.Module._load (module.js:497:3)
2020-09-18T18:03:56:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:03:56:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:03:56: npm
2020-09-18T18:03:56:  ERR! code ELIFECYCLE
2020-09-18T18:03:56: npm 
2020-09-18T18:03:56: ERR! errno 1
2020-09-18T18:03:56: npm
2020-09-18T18:03:56:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:03:56: npm ERR! Exit status 1
2020-09-18T18:03:56: npm ERR! 
2020-09-18T18:03:56: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:03:56: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:03:58: 
2020-09-18T18:03:58: npm ERR! A complete log of this run can be found in:
2020-09-18T18:03:58: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_03_56_088Z-debug.log
2020-09-18T18:04:03: internal/fs.js:55
2020-09-18T18:04:03:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:03:   ^
2020-09-18T18:04:03: 
2020-09-18T18:04:03: Error: Unknown file open flag: undefined
2020-09-18T18:04:03:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:03:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:03:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:03:     at Module._compile (module.js:652:30)
2020-09-18T18:04:03:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:03:     at Module.load (module.js:565:32)
2020-09-18T18:04:03:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:03:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:03:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:03:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:03: npm
2020-09-18T18:04:03:  ERR! code ELIFECYCLE
2020-09-18T18:04:03: npm ERR!
2020-09-18T18:04:03:  errno 1
2020-09-18T18:04:03: npm
2020-09-18T18:04:03:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:03: npm ERR! Exit status 1
2020-09-18T18:04:03: npm ERR! 
2020-09-18T18:04:03:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:03: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:05: 
2020-09-18T18:04:05: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:05: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_03_308Z-debug.log
2020-09-18T18:04:10: internal/fs.js:55
2020-09-18T18:04:10:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:10:   ^
2020-09-18T18:04:10: 
2020-09-18T18:04:10: Error: Unknown file open flag: undefined
2020-09-18T18:04:10:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:10:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:10:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:10:     at Module._compile (module.js:652:30)
2020-09-18T18:04:10:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:10:     at Module.load (module.js:565:32)
2020-09-18T18:04:10:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:10:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:10:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:10:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:10: npm
2020-09-18T18:04:10:  ERR! code ELIFECYCLE
2020-09-18T18:04:10: npm ERR! errno 1
2020-09-18T18:04:10: npm
2020-09-18T18:04:10:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:10: npm ERR! Exit status 1
2020-09-18T18:04:10:  ERR! 
2020-09-18T18:04:10: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:10: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:12: 
2020-09-18T18:04:12: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:12: ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_10_434Z-debug.log
2020-09-18T18:04:17: internal/fs.js:55
2020-09-18T18:04:17:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:17:   ^
2020-09-18T18:04:17: 
2020-09-18T18:04:17: Error: Unknown file open flag: undefined
2020-09-18T18:04:17:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:17:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:17:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:17:     at Module._compile (module.js:652:30)
2020-09-18T18:04:17:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:17:     at Module.load (module.js:565:32)
2020-09-18T18:04:17:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:17:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:17:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:17:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:17: npm
2020-09-18T18:04:17:  ERR! code ELIFECYCLE
2020-09-18T18:04:17: npm
2020-09-18T18:04:17:  ERR! errno 1
2020-09-18T18:04:17: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:17: npm ERR! Exit status 1
2020-09-18T18:04:17: npm ERR! 
2020-09-18T18:04:17: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:17: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:19: 
2020-09-18T18:04:19: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:19:      /home/volumio/.npm/_logs/2020-09-18T10_04_17_565Z-debug.log
2020-09-18T18:04:24: internal/fs.js:55
2020-09-18T18:04:24:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:24:   ^
2020-09-18T18:04:24: 
2020-09-18T18:04:24: Error: Unknown file open flag: undefined
2020-09-18T18:04:24:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:24:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:24:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:24:     at Module._compile (module.js:652:30)
2020-09-18T18:04:24:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:24:     at Module.load (module.js:565:32)
2020-09-18T18:04:24:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:24:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:24:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:24:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:24: npm
2020-09-18T18:04:24:  
2020-09-18T18:04:24: ERR! code ELIFECYCLE
2020-09-18T18:04:24: npm 
2020-09-18T18:04:24: ERR! errno
2020-09-18T18:04:24:  1
2020-09-18T18:04:24: npm
2020-09-18T18:04:24:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:24: npm ERR! Exit status 1
2020-09-18T18:04:24:  ERR! 
2020-09-18T18:04:24: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:24: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:27: 
2020-09-18T18:04:27: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:27: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_24_237Z-debug.log
2020-09-18T18:04:31: internal/fs.js:55
2020-09-18T18:04:31:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:31:   ^
2020-09-18T18:04:31: 
2020-09-18T18:04:31: Error: Unknown file open flag: undefined
2020-09-18T18:04:31:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:31:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:31:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:31:     at Module._compile (module.js:652:30)
2020-09-18T18:04:31:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:31:     at Module.load (module.js:565:32)
2020-09-18T18:04:31:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:31:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:31:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:31:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:31: npm
2020-09-18T18:04:31:  ERR! code ELIFECYCLE
2020-09-18T18:04:31: npm ERR! errno 1
2020-09-18T18:04:31: npm
2020-09-18T18:04:31:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:31: npm ERR! Exit status 1
2020-09-18T18:04:31: npm ERR! 
2020-09-18T18:04:31: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:31: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:34: 
2020-09-18T18:04:34: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:34: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_31_684Z-debug.log
2020-09-18T18:04:38: internal/fs.js:55
2020-09-18T18:04:38:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:38:   ^
2020-09-18T18:04:38: 
2020-09-18T18:04:38: Error: Unknown file open flag: undefined
2020-09-18T18:04:38:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:38:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:38:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:38:     at Module._compile (module.js:652:30)
2020-09-18T18:04:38:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:38:     at Module.load (module.js:565:32)
2020-09-18T18:04:38:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:38:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:38:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:38:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:38: npm
2020-09-18T18:04:38:  ERR! code ELIFECYCLE
2020-09-18T18:04:38: npm ERR! errno 1
2020-09-18T18:04:38: npm
2020-09-18T18:04:38:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:38: npm ERR! Exit status 1
2020-09-18T18:04:38: npm ERR! 
2020-09-18T18:04:38: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:38:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:41: 
2020-09-18T18:04:41: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:41: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_38_663Z-debug.log
2020-09-18T18:04:46: internal/fs.js:55
2020-09-18T18:04:46:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:46:   ^
2020-09-18T18:04:46: 
2020-09-18T18:04:46: Error: Unknown file open flag: undefined
2020-09-18T18:04:46:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:46:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:46:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:46:     at Module._compile (module.js:652:30)
2020-09-18T18:04:46:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:46:     at Module.load (module.js:565:32)
2020-09-18T18:04:46:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:46:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:46:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:46:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:46: npm ERR! code ELIFECYCLE
2020-09-18T18:04:46: npm ERR! errno 1
2020-09-18T18:04:46: npm
2020-09-18T18:04:46:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:46: npm ERR! Exit status 1
2020-09-18T18:04:46: npm
2020-09-18T18:04:46:  ERR! 
2020-09-18T18:04:46:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:46: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:48: 
2020-09-18T18:04:48: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:48:  ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_46_166Z-debug.log
2020-09-18T18:04:53: internal/fs.js:55
2020-09-18T18:04:53:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:53:   ^
2020-09-18T18:04:53: 
2020-09-18T18:04:53: Error: Unknown file open flag: undefined
2020-09-18T18:04:53:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:53:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:53:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:53:     at Module._compile (module.js:652:30)
2020-09-18T18:04:53:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:53:     at Module.load (module.js:565:32)
2020-09-18T18:04:53:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:53:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:53:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:53:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:53: npm ERR! code ELIFECYCLE
2020-09-18T18:04:53: npm ERR!
2020-09-18T18:04:53:  errno 1
2020-09-18T18:04:53: npm
2020-09-18T18:04:53:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:53: npm ERR! Exit status 1
2020-09-18T18:04:53: npm ERR! 
2020-09-18T18:04:53: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:53: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:04:55: 
2020-09-18T18:04:55: npm ERR! A complete log of this run can be found in:
2020-09-18T18:04:55: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_53_158Z-debug.log
2020-09-18T18:04:59: internal/fs.js:55
2020-09-18T18:04:59:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:04:59:   ^
2020-09-18T18:04:59: 
2020-09-18T18:04:59: Error: Unknown file open flag: undefined
2020-09-18T18:04:59:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:04:59:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:04:59:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:04:59:     at Module._compile (module.js:652:30)
2020-09-18T18:04:59:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:04:59:     at Module.load (module.js:565:32)
2020-09-18T18:04:59:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:04:59:     at Function.Module._load (module.js:497:3)
2020-09-18T18:04:59:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:04:59:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:04:59: npm
2020-09-18T18:04:59:  
2020-09-18T18:04:59: ERR!
2020-09-18T18:04:59:  
2020-09-18T18:04:59: code
2020-09-18T18:04:59:  ELIFECYCLE
2020-09-18T18:04:59:  ERR! errno 1
2020-09-18T18:04:59: npm
2020-09-18T18:04:59:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:04:59: npm ERR! Exit status 1
2020-09-18T18:04:59: npm ERR! 
2020-09-18T18:04:59:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:04:59: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:02: 
2020-09-18T18:05:02: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:02: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_04_59_859Z-debug.log
2020-09-18T18:05:07: internal/fs.js:55
2020-09-18T18:05:07:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:07:   ^
2020-09-18T18:05:07: 
2020-09-18T18:05:07: Error: Unknown file open flag: undefined
2020-09-18T18:05:07:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:07:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:07:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:07:     at Module._compile (module.js:652:30)
2020-09-18T18:05:07:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:07:     at Module.load (module.js:565:32)
2020-09-18T18:05:07:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:07:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:07:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:07:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:07: npm
2020-09-18T18:05:07:  ERR! code ELIFECYCLE
2020-09-18T18:05:07: npm 
2020-09-18T18:05:07: ERR! errno 1
2020-09-18T18:05:07: npm
2020-09-18T18:05:07:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:07: npm ERR! Exit status 1
2020-09-18T18:05:07: npm ERR! 
2020-09-18T18:05:07: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:07: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:09: 
2020-09-18T18:05:09: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:09: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_07_705Z-debug.log
2020-09-18T18:05:14: internal/fs.js:55
2020-09-18T18:05:14:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:14:   ^
2020-09-18T18:05:14: 
2020-09-18T18:05:14: Error: Unknown file open flag: undefined
2020-09-18T18:05:14:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:14:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:14:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:14:     at Module._compile (module.js:652:30)
2020-09-18T18:05:14:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:14:     at Module.load (module.js:565:32)
2020-09-18T18:05:14:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:14:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:14:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:14:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:14: npm
2020-09-18T18:05:14:  ERR! code ELIFECYCLE
2020-09-18T18:05:14: ERR! errno 1
2020-09-18T18:05:14: npm
2020-09-18T18:05:14:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:14: npm ERR! Exit status 1
2020-09-18T18:05:14:  
2020-09-18T18:05:14: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:14: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:16: 
2020-09-18T18:05:16: npm
2020-09-18T18:05:16:  ERR! A complete log of this run can be found in:
2020-09-18T18:05:16: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_14_519Z-debug.log
2020-09-18T18:05:21: internal/fs.js:55
2020-09-18T18:05:21:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:21:   ^
2020-09-18T18:05:21: 
2020-09-18T18:05:21: Error: Unknown file open flag: undefined
2020-09-18T18:05:21:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:21:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:21:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:21:     at Module._compile (module.js:652:30)
2020-09-18T18:05:21:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:21:     at Module.load (module.js:565:32)
2020-09-18T18:05:21:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:21:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:21:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:21:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:21: npm
2020-09-18T18:05:21:  ERR! code ELIFECYCLE
2020-09-18T18:05:21: npm ERR! errno 1
2020-09-18T18:05:21: npm
2020-09-18T18:05:21:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:21: npm ERR! Exit status 1
2020-09-18T18:05:21:  
2020-09-18T18:05:21: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:21: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:23: 
2020-09-18T18:05:23: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:23: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_21_077Z-debug.log
2020-09-18T18:05:28: internal/fs.js:55
2020-09-18T18:05:28:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:28:   ^
2020-09-18T18:05:28: 
2020-09-18T18:05:28: Error: Unknown file open flag: undefined
2020-09-18T18:05:28:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:28:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:28:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:28:     at Module._compile (module.js:652:30)
2020-09-18T18:05:28:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:28:     at Module.load (module.js:565:32)
2020-09-18T18:05:28:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:28:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:28:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:28:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:28: npm
2020-09-18T18:05:28:  ERR! code ELIFECYCLE
2020-09-18T18:05:28: npm
2020-09-18T18:05:28:  ERR! errno 1
2020-09-18T18:05:28: npm
2020-09-18T18:05:28:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:28:  Exit status 1
2020-09-18T18:05:28: npm ERR! 
2020-09-18T18:05:28: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:28: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:31: 
2020-09-18T18:05:31: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:31: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_28_842Z-debug.log
2020-09-18T18:05:35: internal/fs.js:55
2020-09-18T18:05:35:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:35:   ^
2020-09-18T18:05:35: 
2020-09-18T18:05:35: Error: Unknown file open flag: undefined
2020-09-18T18:05:35:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:35:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:35:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:35:     at Module._compile (module.js:652:30)
2020-09-18T18:05:35:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:35:     at Module.load (module.js:565:32)
2020-09-18T18:05:35:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:35:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:35:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:35:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:35: npm
2020-09-18T18:05:35:  
2020-09-18T18:05:35: ERR!
2020-09-18T18:05:35:  
2020-09-18T18:05:35: code
2020-09-18T18:05:35:  ELIFECYCLE
2020-09-18T18:05:35:  errno 1
2020-09-18T18:05:35: npm
2020-09-18T18:05:35:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:35: npm ERR! Exit status 1
2020-09-18T18:05:35: npm ERR! 
2020-09-18T18:05:35: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:35:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:38: 
2020-09-18T18:05:38: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:38: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_35_574Z-debug.log
2020-09-18T18:05:42: internal/fs.js:55
2020-09-18T18:05:42:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:42:   ^
2020-09-18T18:05:42: 
2020-09-18T18:05:42: Error: Unknown file open flag: undefined
2020-09-18T18:05:42:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:42:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:42:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:42:     at Module._compile (module.js:652:30)
2020-09-18T18:05:42:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:42:     at Module.load (module.js:565:32)
2020-09-18T18:05:42:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:42:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:42:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:42:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:42: npm
2020-09-18T18:05:42:  ERR! code ELIFECYCLE
2020-09-18T18:05:42: npm ERR! errno
2020-09-18T18:05:42:  1
2020-09-18T18:05:42: npm
2020-09-18T18:05:42:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:42: npm ERR! Exit status 1
2020-09-18T18:05:42: npm ERR! 
2020-09-18T18:05:42: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:42: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:42: 
2020-09-18T18:05:42: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:42: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_42_319Z-debug.log
2020-09-18T18:05:46: internal/fs.js:55
2020-09-18T18:05:46:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:46:   ^
2020-09-18T18:05:46: 
2020-09-18T18:05:46: Error: Unknown file open flag: undefined
2020-09-18T18:05:46:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:46:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:46:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:46:     at Module._compile (module.js:652:30)
2020-09-18T18:05:46:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:46:     at Module.load (module.js:565:32)
2020-09-18T18:05:46:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:46:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:46:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:46:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:46: npm
2020-09-18T18:05:46:  ERR! code ELIFECYCLE
2020-09-18T18:05:46: npm ERR! 
2020-09-18T18:05:46: errno 1
2020-09-18T18:05:46: npm
2020-09-18T18:05:46:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:47: npm ERR! Exit status 1
2020-09-18T18:05:47: npm ERR! 
2020-09-18T18:05:47: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:47:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:49: 
2020-09-18T18:05:49: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:49:      /home/volumio/.npm/_logs/2020-09-18T10_05_47_013Z-debug.log
2020-09-18T18:05:54: internal/fs.js:55
2020-09-18T18:05:54:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:05:54:   ^
2020-09-18T18:05:54: 
2020-09-18T18:05:54: Error: Unknown file open flag: undefined
2020-09-18T18:05:54:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:05:54:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:05:54:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:05:54:     at Module._compile (module.js:652:30)
2020-09-18T18:05:54:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:05:54:     at Module.load (module.js:565:32)
2020-09-18T18:05:54:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:05:54:     at Function.Module._load (module.js:497:3)
2020-09-18T18:05:54:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:05:54:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:05:54: npm
2020-09-18T18:05:54:  ERR! code ELIFECYCLE
2020-09-18T18:05:54: npm
2020-09-18T18:05:54:  ERR! errno 1
2020-09-18T18:05:54: npm ERR!
2020-09-18T18:05:54:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:05:54: npm ERR! Exit status 1
2020-09-18T18:05:54: npm ERR! 
2020-09-18T18:05:54: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:05:54:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:05:56: 
2020-09-18T18:05:56: npm ERR! A complete log of this run can be found in:
2020-09-18T18:05:56: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_05_54_533Z-debug.log
2020-09-18T18:06:01: internal/fs.js:55
2020-09-18T18:06:01:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:01:   ^
2020-09-18T18:06:01: 
2020-09-18T18:06:01: Error: Unknown file open flag: undefined
2020-09-18T18:06:01:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:01:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:01:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:01:     at Module._compile (module.js:652:30)
2020-09-18T18:06:01:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:01:     at Module.load (module.js:565:32)
2020-09-18T18:06:01:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:01:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:01:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:01:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:01: npm
2020-09-18T18:06:01:  ERR! code ELIFECYCLE
2020-09-18T18:06:01: npm ERR! errno 1
2020-09-18T18:06:01: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:01: npm ERR! Exit status 1
2020-09-18T18:06:01: npm ERR! 
2020-09-18T18:06:01: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:01: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:03: 
2020-09-18T18:06:03: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:03: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_01_712Z-debug.log
2020-09-18T18:06:08: internal/fs.js:55
2020-09-18T18:06:08:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:08:   ^
2020-09-18T18:06:08: 
2020-09-18T18:06:08: Error: Unknown file open flag: undefined
2020-09-18T18:06:08:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:08:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:08:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:08:     at Module._compile (module.js:652:30)
2020-09-18T18:06:08:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:08:     at Module.load (module.js:565:32)
2020-09-18T18:06:08:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:08:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:08:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:08:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:08: npm
2020-09-18T18:06:08:  
2020-09-18T18:06:08: ERR!
2020-09-18T18:06:08:  
2020-09-18T18:06:08: code
2020-09-18T18:06:08:  ELIFECYCLE
2020-09-18T18:06:08: npm
2020-09-18T18:06:08:  
2020-09-18T18:06:08: ERR! errno 1
2020-09-18T18:06:08: npm
2020-09-18T18:06:08:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:08: npm ERR! Exit status 1
2020-09-18T18:06:08: npm
2020-09-18T18:06:08:  ERR! 
2020-09-18T18:06:08:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:08: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:10: 
2020-09-18T18:06:10: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:10: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_08_202Z-debug.log
2020-09-18T18:06:15: internal/fs.js:55
2020-09-18T18:06:15:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:15:   ^
2020-09-18T18:06:15: 
2020-09-18T18:06:15: Error: Unknown file open flag: undefined
2020-09-18T18:06:15:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:15:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:15:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:15:     at Module._compile (module.js:652:30)
2020-09-18T18:06:15:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:15:     at Module.load (module.js:565:32)
2020-09-18T18:06:15:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:15:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:15:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:15:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:15: npm
2020-09-18T18:06:15:  
2020-09-18T18:06:15: ERR! code ELIFECYCLE
2020-09-18T18:06:15:  ERR! errno 1
2020-09-18T18:06:15: npm
2020-09-18T18:06:15:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:15: npm ERR! Exit status 1
2020-09-18T18:06:15:  ERR! 
2020-09-18T18:06:15: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:15: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:17: 
2020-09-18T18:06:17: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:17: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_15_599Z-debug.log
2020-09-18T18:06:22: internal/fs.js:55
2020-09-18T18:06:22:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:22:   ^
2020-09-18T18:06:22: 
2020-09-18T18:06:22: Error: Unknown file open flag: undefined
2020-09-18T18:06:22:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:22:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:22:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:22:     at Module._compile (module.js:652:30)
2020-09-18T18:06:22:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:22:     at Module.load (module.js:565:32)
2020-09-18T18:06:22:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:22:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:22:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:22:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:22: npm ERR! code ELIFECYCLE
2020-09-18T18:06:22: npm ERR!
2020-09-18T18:06:22:  errno 1
2020-09-18T18:06:22: npm
2020-09-18T18:06:22:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:22: npm ERR! Exit status 1
2020-09-18T18:06:22: npm ERR! 
2020-09-18T18:06:22: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:22: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:25: 
2020-09-18T18:06:25: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:25: ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_22_856Z-debug.log
2020-09-18T18:06:29: internal/fs.js:55
2020-09-18T18:06:29:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:29:   ^
2020-09-18T18:06:29: 
2020-09-18T18:06:29: Error: Unknown file open flag: undefined
2020-09-18T18:06:29:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:29:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:29:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:29:     at Module._compile (module.js:652:30)
2020-09-18T18:06:29:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:29:     at Module.load (module.js:565:32)
2020-09-18T18:06:29:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:29:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:29:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:29:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:29: npm
2020-09-18T18:06:29:  ERR! code ELIFECYCLE
2020-09-18T18:06:29: npm ERR! errno 1
2020-09-18T18:06:29: npm
2020-09-18T18:06:29:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:29: npm ERR! Exit status 1
2020-09-18T18:06:29: npm ERR! 
2020-09-18T18:06:29: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:29:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:31: 
2020-09-18T18:06:31: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:31: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_29_590Z-debug.log
2020-09-18T18:06:36: internal/fs.js:55
2020-09-18T18:06:36:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:36:   ^
2020-09-18T18:06:36: 
2020-09-18T18:06:36: Error: Unknown file open flag: undefined
2020-09-18T18:06:36:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:36:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:36:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:36:     at Module._compile (module.js:652:30)
2020-09-18T18:06:36:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:36:     at Module.load (module.js:565:32)
2020-09-18T18:06:36:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:36:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:36:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:36:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:36: npm
2020-09-18T18:06:36:  ERR! code ELIFECYCLE
2020-09-18T18:06:36: npm
2020-09-18T18:06:36:  ERR! errno 1
2020-09-18T18:06:36: npm
2020-09-18T18:06:36:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:36: npm ERR! Exit status 1
2020-09-18T18:06:36: npm
2020-09-18T18:06:36:  ERR! 
2020-09-18T18:06:36:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:36: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:39: 
2020-09-18T18:06:39: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:39: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_36_354Z-debug.log
2020-09-18T18:06:43: internal/fs.js:55
2020-09-18T18:06:43:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:43:   ^
2020-09-18T18:06:43: 
2020-09-18T18:06:43: Error: Unknown file open flag: undefined
2020-09-18T18:06:43:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:43:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:43:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:43:     at Module._compile (module.js:652:30)
2020-09-18T18:06:43:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:43:     at Module.load (module.js:565:32)
2020-09-18T18:06:43:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:43:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:43:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:43:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:43: npm
2020-09-18T18:06:43:  ERR! code ELIFECYCLE
2020-09-18T18:06:43: errno 1
2020-09-18T18:06:43: npm
2020-09-18T18:06:43:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:43: npm ERR! Exit status 1
2020-09-18T18:06:43: npm ERR! 
2020-09-18T18:06:43: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:43: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:46: 
2020-09-18T18:06:46: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:46: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_43_312Z-debug.log
2020-09-18T18:06:50: internal/fs.js:55
2020-09-18T18:06:50:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:50:   ^
2020-09-18T18:06:50: 
2020-09-18T18:06:50: Error: Unknown file open flag: undefined
2020-09-18T18:06:50:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:50:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:50:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:50:     at Module._compile (module.js:652:30)
2020-09-18T18:06:50:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:50:     at Module.load (module.js:565:32)
2020-09-18T18:06:50:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:50:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:50:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:50:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:50: npm
2020-09-18T18:06:50:  
2020-09-18T18:06:50: ERR! code ELIFECYCLE
2020-09-18T18:06:50: npm ERR! errno 1
2020-09-18T18:06:50: npm
2020-09-18T18:06:50:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:50: npm ERR! Exit status 1
2020-09-18T18:06:50: npm ERR! 
2020-09-18T18:06:50: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:50:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:53: 
2020-09-18T18:06:53: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:53: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_50_684Z-debug.log
2020-09-18T18:06:57: internal/fs.js:55
2020-09-18T18:06:57:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:06:57:   ^
2020-09-18T18:06:57: 
2020-09-18T18:06:57: Error: Unknown file open flag: undefined
2020-09-18T18:06:57:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:06:57:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:06:57:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:06:57:     at Module._compile (module.js:652:30)
2020-09-18T18:06:57:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:06:57:     at Module.load (module.js:565:32)
2020-09-18T18:06:57:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:06:57:     at Function.Module._load (module.js:497:3)
2020-09-18T18:06:57:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:06:57:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:06:57: npm
2020-09-18T18:06:57:  ERR! code ELIFECYCLE
2020-09-18T18:06:57:  errno 1
2020-09-18T18:06:57: npm
2020-09-18T18:06:57:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:06:57: npm ERR! Exit status 1
2020-09-18T18:06:57:  
2020-09-18T18:06:57: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:06:57: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:06:59: 
2020-09-18T18:06:59: npm ERR! A complete log of this run can be found in:
2020-09-18T18:06:59: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_06_57_342Z-debug.log
2020-09-18T18:07:04: internal/fs.js:55
2020-09-18T18:07:04:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:04:   ^
2020-09-18T18:07:04: 
2020-09-18T18:07:04: Error: Unknown file open flag: undefined
2020-09-18T18:07:04:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:04:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:04:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:04:     at Module._compile (module.js:652:30)
2020-09-18T18:07:04:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:04:     at Module.load (module.js:565:32)
2020-09-18T18:07:04:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:04:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:04:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:04:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:04: npm
2020-09-18T18:07:04:  
2020-09-18T18:07:04: ERR!
2020-09-18T18:07:04:  code
2020-09-18T18:07:04:  ELIFECYCLE
2020-09-18T18:07:04: npm
2020-09-18T18:07:04:  ERR! errno 1
2020-09-18T18:07:04: npm
2020-09-18T18:07:04:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:04:  Exit status 1
2020-09-18T18:07:04: npm 
2020-09-18T18:07:04: ERR!
2020-09-18T18:07:04:  
2020-09-18T18:07:04:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:04: npm ERR!
2020-09-18T18:07:04:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:07: 
2020-09-18T18:07:07: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:07: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_04_833Z-debug.log
2020-09-18T18:07:11: internal/fs.js:55
2020-09-18T18:07:11:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:11:   ^
2020-09-18T18:07:11: 
2020-09-18T18:07:11: Error: Unknown file open flag: undefined
2020-09-18T18:07:11:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:11:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:11:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:11:     at Module._compile (module.js:652:30)
2020-09-18T18:07:11:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:11:     at Module.load (module.js:565:32)
2020-09-18T18:07:11:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:11:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:11:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:11:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:11: npm
2020-09-18T18:07:11:  ERR! code ELIFECYCLE
2020-09-18T18:07:11: npm ERR! errno 1
2020-09-18T18:07:11: npm
2020-09-18T18:07:11:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:11: npm ERR! Exit status 1
2020-09-18T18:07:11: npm ERR! 
2020-09-18T18:07:11:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:11: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:14: 
2020-09-18T18:07:14: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:14: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_11_822Z-debug.log
2020-09-18T18:07:18: internal/fs.js:55
2020-09-18T18:07:18:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:18:   ^
2020-09-18T18:07:18: 
2020-09-18T18:07:18: Error: Unknown file open flag: undefined
2020-09-18T18:07:18:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:18:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:18:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:18:     at Module._compile (module.js:652:30)
2020-09-18T18:07:18:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:18:     at Module.load (module.js:565:32)
2020-09-18T18:07:18:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:18:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:18:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:18:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:18: npm
2020-09-18T18:07:18:  ERR! code ELIFECYCLE
2020-09-18T18:07:18: npm
2020-09-18T18:07:18:  ERR! errno 1
2020-09-18T18:07:18: npm
2020-09-18T18:07:18:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:18: npm ERR! Exit status 1
2020-09-18T18:07:18: npm
2020-09-18T18:07:18:  ERR! 
2020-09-18T18:07:18:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:18: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:21: 
2020-09-18T18:07:21: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:21: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_18_372Z-debug.log
2020-09-18T18:07:25: internal/fs.js:55
2020-09-18T18:07:25:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:25:   ^
2020-09-18T18:07:25: 
2020-09-18T18:07:25: Error: Unknown file open flag: undefined
2020-09-18T18:07:25:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:25:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:25:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:25:     at Module._compile (module.js:652:30)
2020-09-18T18:07:25:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:25:     at Module.load (module.js:565:32)
2020-09-18T18:07:25:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:25:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:25:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:25:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:25: npm
2020-09-18T18:07:25:  
2020-09-18T18:07:25: ERR! code ELIFECYCLE
2020-09-18T18:07:25: npm ERR! errno 1
2020-09-18T18:07:25: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:25: npm ERR! Exit status 1
2020-09-18T18:07:25: npm ERR! 
2020-09-18T18:07:25: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:25: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:28: 
2020-09-18T18:07:28: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:28: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_25_559Z-debug.log
2020-09-18T18:07:33: internal/fs.js:55
2020-09-18T18:07:33:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:33:   ^
2020-09-18T18:07:33: 
2020-09-18T18:07:33: Error: Unknown file open flag: undefined
2020-09-18T18:07:33:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:33:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:33:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:33:     at Module._compile (module.js:652:30)
2020-09-18T18:07:33:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:33:     at Module.load (module.js:565:32)
2020-09-18T18:07:33:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:33:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:33:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:33:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:33: npm
2020-09-18T18:07:33:  ERR! code ELIFECYCLE
2020-09-18T18:07:33: npm ERR! errno 1
2020-09-18T18:07:33: npm
2020-09-18T18:07:33:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:33: npm ERR! Exit status 1
2020-09-18T18:07:33: npm ERR! 
2020-09-18T18:07:33: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:33:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:35: 
2020-09-18T18:07:35: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:35: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_33_073Z-debug.log
2020-09-18T18:07:39: internal/fs.js:55
2020-09-18T18:07:39:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:39:   ^
2020-09-18T18:07:39: 
2020-09-18T18:07:39: Error: Unknown file open flag: undefined
2020-09-18T18:07:39:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:39:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:39:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:39:     at Module._compile (module.js:652:30)
2020-09-18T18:07:39:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:39:     at Module.load (module.js:565:32)
2020-09-18T18:07:39:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:39:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:39:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:39:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:39: npm
2020-09-18T18:07:39:  
2020-09-18T18:07:39: ERR! code ELIFECYCLE
2020-09-18T18:07:39:  ERR! errno 1
2020-09-18T18:07:39: npm
2020-09-18T18:07:39:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:39: npm ERR! Exit status 1
2020-09-18T18:07:39: npm ERR! 
2020-09-18T18:07:39: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:39:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:42: 
2020-09-18T18:07:42: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:42: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_39_578Z-debug.log
2020-09-18T18:07:46: internal/fs.js:55
2020-09-18T18:07:46:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:46:   ^
2020-09-18T18:07:46: 
2020-09-18T18:07:46: Error: Unknown file open flag: undefined
2020-09-18T18:07:46:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:46:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:46:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:46:     at Module._compile (module.js:652:30)
2020-09-18T18:07:46:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:46:     at Module.load (module.js:565:32)
2020-09-18T18:07:46:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:46:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:46:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:46:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:46: npm
2020-09-18T18:07:46:  ERR! code ELIFECYCLE
2020-09-18T18:07:46: npm ERR! errno 1
2020-09-18T18:07:46: npm
2020-09-18T18:07:46:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:46: npm ERR! Exit status 1
2020-09-18T18:07:46: npm ERR! 
2020-09-18T18:07:46: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:46:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:49: 
2020-09-18T18:07:49: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:49: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_46_583Z-debug.log
2020-09-18T18:07:53: internal/fs.js:55
2020-09-18T18:07:53:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:07:53:   ^
2020-09-18T18:07:53: 
2020-09-18T18:07:53: Error: Unknown file open flag: undefined
2020-09-18T18:07:53:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:07:53:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:07:53:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:07:53:     at Module._compile (module.js:652:30)
2020-09-18T18:07:53:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:07:53:     at Module.load (module.js:565:32)
2020-09-18T18:07:53:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:07:53:     at Function.Module._load (module.js:497:3)
2020-09-18T18:07:53:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:07:53:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:07:53: npm
2020-09-18T18:07:53:  ERR! code ELIFECYCLE
2020-09-18T18:07:53: errno 1
2020-09-18T18:07:53: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:07:53: npm ERR! Exit status 1
2020-09-18T18:07:53: npm ERR! 
2020-09-18T18:07:53:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:07:53: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:07:56: 
2020-09-18T18:07:56: npm ERR! A complete log of this run can be found in:
2020-09-18T18:07:56: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_07_53_825Z-debug.log
2020-09-18T18:08:01: internal/fs.js:55
2020-09-18T18:08:01:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:01:   ^
2020-09-18T18:08:01: 
2020-09-18T18:08:01: Error: Unknown file open flag: undefined
2020-09-18T18:08:01:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:01:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:01:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:01:     at Module._compile (module.js:652:30)
2020-09-18T18:08:01:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:01:     at Module.load (module.js:565:32)
2020-09-18T18:08:01:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:01:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:01:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:01:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:01: npm ERR! code ELIFECYCLE
2020-09-18T18:08:01: npm ERR! errno 1
2020-09-18T18:08:01: npm
2020-09-18T18:08:01:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:01: npm ERR! Exit status 1
2020-09-18T18:08:01: npm ERR! 
2020-09-18T18:08:01: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:01: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:03: 
2020-09-18T18:08:03: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:03: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_01_218Z-debug.log
2020-09-18T18:08:07: internal/fs.js:55
2020-09-18T18:08:07:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:07:   ^
2020-09-18T18:08:07: 
2020-09-18T18:08:07: Error: Unknown file open flag: undefined
2020-09-18T18:08:07:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:07:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:07:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:07:     at Module._compile (module.js:652:30)
2020-09-18T18:08:07:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:07:     at Module.load (module.js:565:32)
2020-09-18T18:08:07:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:07:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:07:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:07:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:07: npm
2020-09-18T18:08:07:  ERR! code ELIFECYCLE
2020-09-18T18:08:07: npm ERR!
2020-09-18T18:08:07:  errno 1
2020-09-18T18:08:07: npm
2020-09-18T18:08:07:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:07: npm ERR! Exit status 1
2020-09-18T18:08:07: npm ERR! 
2020-09-18T18:08:07:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:07: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:10: 
2020-09-18T18:08:10: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:10:      /home/volumio/.npm/_logs/2020-09-18T10_08_07_679Z-debug.log
2020-09-18T18:08:14: internal/fs.js:55
2020-09-18T18:08:14:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:14:   ^
2020-09-18T18:08:14: 
2020-09-18T18:08:14: Error: Unknown file open flag: undefined
2020-09-18T18:08:14:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:14:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:14:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:14:     at Module._compile (module.js:652:30)
2020-09-18T18:08:14:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:14:     at Module.load (module.js:565:32)
2020-09-18T18:08:14:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:14:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:14:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:14:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:14: npm ERR! code ELIFECYCLE
2020-09-18T18:08:14: npm ERR! errno 1
2020-09-18T18:08:14: npm ERR!
2020-09-18T18:08:14:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:14: npm ERR! Exit status 1
2020-09-18T18:08:14: npm ERR! 
2020-09-18T18:08:14: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:14: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:17: 
2020-09-18T18:08:17: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:17:  ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_14_731Z-debug.log
2020-09-18T18:08:21: internal/fs.js:55
2020-09-18T18:08:21:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:21:   ^
2020-09-18T18:08:21: 
2020-09-18T18:08:21: Error: Unknown file open flag: undefined
2020-09-18T18:08:21:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:21:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:21:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:21:     at Module._compile (module.js:652:30)
2020-09-18T18:08:21:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:21:     at Module.load (module.js:565:32)
2020-09-18T18:08:21:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:21:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:21:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:21:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:21: npm
2020-09-18T18:08:21:  ERR! code ELIFECYCLE
2020-09-18T18:08:21: npm ERR! errno 1
2020-09-18T18:08:21: npm
2020-09-18T18:08:21:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:21: npm ERR! Exit status 1
2020-09-18T18:08:21: npm ERR! 
2020-09-18T18:08:21: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:21: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:24: 
2020-09-18T18:08:24: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:24: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_21_987Z-debug.log
2020-09-18T18:08:29: internal/fs.js:55
2020-09-18T18:08:29:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:29:   ^
2020-09-18T18:08:29: 
2020-09-18T18:08:29: Error: Unknown file open flag: undefined
2020-09-18T18:08:29:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:29:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:29:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:29:     at Module._compile (module.js:652:30)
2020-09-18T18:08:29:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:29:     at Module.load (module.js:565:32)
2020-09-18T18:08:29:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:29:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:29:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:29:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:29: npm
2020-09-18T18:08:29:  ERR! code ELIFECYCLE
2020-09-18T18:08:29: npm ERR! errno 1
2020-09-18T18:08:29: npm
2020-09-18T18:08:29:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:29: npm ERR! Exit status 1
2020-09-18T18:08:29: npm ERR! 
2020-09-18T18:08:29: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:29: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:31: 
2020-09-18T18:08:31: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:31: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_29_077Z-debug.log
2020-09-18T18:08:35: internal/fs.js:55
2020-09-18T18:08:35:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:35:   ^
2020-09-18T18:08:35: 
2020-09-18T18:08:35: Error: Unknown file open flag: undefined
2020-09-18T18:08:35:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:35:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:35:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:35:     at Module._compile (module.js:652:30)
2020-09-18T18:08:35:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:35:     at Module.load (module.js:565:32)
2020-09-18T18:08:35:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:35:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:35:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:35:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:35: npm
2020-09-18T18:08:35:  ERR! code ELIFECYCLE
2020-09-18T18:08:35: npm
2020-09-18T18:08:35:  ERR! errno 1
2020-09-18T18:08:35: npm
2020-09-18T18:08:35:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:35:  Exit status 1
2020-09-18T18:08:35: npm 
2020-09-18T18:08:35: ERR! 
2020-09-18T18:08:35:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:35: npm ERR!
2020-09-18T18:08:35:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:38: 
2020-09-18T18:08:38: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:38: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_35_642Z-debug.log
2020-09-18T18:08:43: internal/fs.js:55
2020-09-18T18:08:43:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:43:   ^
2020-09-18T18:08:43: 
2020-09-18T18:08:43: Error: Unknown file open flag: undefined
2020-09-18T18:08:43:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:43:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:43:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:43:     at Module._compile (module.js:652:30)
2020-09-18T18:08:43:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:43:     at Module.load (module.js:565:32)
2020-09-18T18:08:43:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:43:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:43:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:43:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:43: npm
2020-09-18T18:08:43:  ERR! code ELIFECYCLE
2020-09-18T18:08:43: npm ERR! errno 1
2020-09-18T18:08:43: npm
2020-09-18T18:08:43:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:43: npm ERR! Exit status 1
2020-09-18T18:08:43: npm ERR! 
2020-09-18T18:08:43: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:43: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:45: 
2020-09-18T18:08:45: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:45: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_43_366Z-debug.log
2020-09-18T18:08:49: internal/fs.js:55
2020-09-18T18:08:49:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:49:   ^
2020-09-18T18:08:49: 
2020-09-18T18:08:49: Error: Unknown file open flag: undefined
2020-09-18T18:08:49:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:49:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:49:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:49:     at Module._compile (module.js:652:30)
2020-09-18T18:08:49:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:49:     at Module.load (module.js:565:32)
2020-09-18T18:08:49:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:49:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:49:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:49:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:49: npm
2020-09-18T18:08:49:  ERR! code ELIFECYCLE
2020-09-18T18:08:49: npm
2020-09-18T18:08:49:  ERR! errno 1
2020-09-18T18:08:49: npm
2020-09-18T18:08:49:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:49: npm ERR! Exit status 1
2020-09-18T18:08:49: npm
2020-09-18T18:08:49:  ERR! 
2020-09-18T18:08:49:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:49: npm ERR!
2020-09-18T18:08:49:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:52: 
2020-09-18T18:08:52: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:52: ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_49_908Z-debug.log
2020-09-18T18:08:55: internal/fs.js:55
2020-09-18T18:08:55:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:08:55:   ^
2020-09-18T18:08:55: 
2020-09-18T18:08:55: Error: Unknown file open flag: undefined
2020-09-18T18:08:55:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:08:55:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:08:55:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:08:55:     at Module._compile (module.js:652:30)
2020-09-18T18:08:55:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:08:55:     at Module.load (module.js:565:32)
2020-09-18T18:08:55:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:08:55:     at Function.Module._load (module.js:497:3)
2020-09-18T18:08:55:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:08:55:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:08:55: npm
2020-09-18T18:08:55:  ERR! code ELIFECYCLE
2020-09-18T18:08:55: npm
2020-09-18T18:08:55:  ERR! errno 1
2020-09-18T18:08:55: npm
2020-09-18T18:08:55:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:08:55: npm ERR! Exit status 1
2020-09-18T18:08:55:  ERR! 
2020-09-18T18:08:55: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:08:55: npm
2020-09-18T18:08:55:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:08:56: 
2020-09-18T18:08:56: npm ERR! A complete log of this run can be found in:
2020-09-18T18:08:56: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_08_55_917Z-debug.log
2020-09-18T18:09:00: internal/fs.js:55
2020-09-18T18:09:00:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:00:   ^
2020-09-18T18:09:00: 
2020-09-18T18:09:00: Error: Unknown file open flag: undefined
2020-09-18T18:09:00:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:00:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:00:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:00:     at Module._compile (module.js:652:30)
2020-09-18T18:09:00:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:00:     at Module.load (module.js:565:32)
2020-09-18T18:09:00:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:00:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:00:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:00:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:01: npm
2020-09-18T18:09:01:  
2020-09-18T18:09:01: ERR! code ELIFECYCLE
2020-09-18T18:09:01: npm ERR! errno
2020-09-18T18:09:01:  1
2020-09-18T18:09:01: npm
2020-09-18T18:09:01:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:01: npm ERR! Exit status 1
2020-09-18T18:09:01: npm ERR! 
2020-09-18T18:09:01: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:01: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:01: 
2020-09-18T18:09:01: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:01: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_01_048Z-debug.log
2020-09-18T18:09:06: internal/fs.js:55
2020-09-18T18:09:06:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:06:   ^
2020-09-18T18:09:06: 
2020-09-18T18:09:06: Error: Unknown file open flag: undefined
2020-09-18T18:09:06:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:06:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:06:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:06:     at Module._compile (module.js:652:30)
2020-09-18T18:09:06:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:06:     at Module.load (module.js:565:32)
2020-09-18T18:09:06:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:06:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:06:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:06:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:06: npm
2020-09-18T18:09:06:  ERR! code ELIFECYCLE
2020-09-18T18:09:06: npm
2020-09-18T18:09:06:  ERR! errno 1
2020-09-18T18:09:06: npm
2020-09-18T18:09:06:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:06:  Exit status 1
2020-09-18T18:09:06: npm
2020-09-18T18:09:06:  ERR! 
2020-09-18T18:09:06: npm ERR!
2020-09-18T18:09:06:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:06:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:08: 
2020-09-18T18:09:08: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:08: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_06_080Z-debug.log
2020-09-18T18:09:13: internal/fs.js:55
2020-09-18T18:09:13:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:13:   ^
2020-09-18T18:09:13: 
2020-09-18T18:09:13: Error: Unknown file open flag: undefined
2020-09-18T18:09:13:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:13:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:13:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:13:     at Module._compile (module.js:652:30)
2020-09-18T18:09:13:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:13:     at Module.load (module.js:565:32)
2020-09-18T18:09:13:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:13:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:13:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:13:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:13: npm
2020-09-18T18:09:13:  ERR! code ELIFECYCLE
2020-09-18T18:09:13: errno 1
2020-09-18T18:09:13: npm
2020-09-18T18:09:13:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:13: npm ERR! Exit status 1
2020-09-18T18:09:13: npm ERR! 
2020-09-18T18:09:13: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:13: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:15: 
2020-09-18T18:09:15: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:15: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_13_640Z-debug.log
2020-09-18T18:09:20: internal/fs.js:55
2020-09-18T18:09:20:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:20:   ^
2020-09-18T18:09:20: 
2020-09-18T18:09:20: Error: Unknown file open flag: undefined
2020-09-18T18:09:20:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:20:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:20:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:20:     at Module._compile (module.js:652:30)
2020-09-18T18:09:20:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:20:     at Module.load (module.js:565:32)
2020-09-18T18:09:20:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:20:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:20:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:20:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:20: npm
2020-09-18T18:09:20:  
2020-09-18T18:09:20: ERR!
2020-09-18T18:09:20:  code ELIFECYCLE
2020-09-18T18:09:20: npm ERR! errno 1
2020-09-18T18:09:20: npm
2020-09-18T18:09:20:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:20: npm ERR! Exit status 1
2020-09-18T18:09:20: npm ERR! 
2020-09-18T18:09:20:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:20: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:22: 
2020-09-18T18:09:22: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:22: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_20_318Z-debug.log
2020-09-18T18:09:27: internal/fs.js:55
2020-09-18T18:09:27:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:27:   ^
2020-09-18T18:09:27: 
2020-09-18T18:09:27: Error: Unknown file open flag: undefined
2020-09-18T18:09:27:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:27:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:27:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:27:     at Module._compile (module.js:652:30)
2020-09-18T18:09:27:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:27:     at Module.load (module.js:565:32)
2020-09-18T18:09:27:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:27:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:27:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:27:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:27: npm
2020-09-18T18:09:27:  ERR! code ELIFECYCLE
2020-09-18T18:09:27: npm
2020-09-18T18:09:27:  ERR! errno 1
2020-09-18T18:09:27: npm
2020-09-18T18:09:27:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:27: ERR! Exit status 1
2020-09-18T18:09:27: npm
2020-09-18T18:09:27:  ERR! 
2020-09-18T18:09:27: npm ERR!
2020-09-18T18:09:27:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:27: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:29: 
2020-09-18T18:09:29: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:29:  ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_27_653Z-debug.log
2020-09-18T18:09:34: internal/fs.js:55
2020-09-18T18:09:34:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:34:   ^
2020-09-18T18:09:34: 
2020-09-18T18:09:34: Error: Unknown file open flag: undefined
2020-09-18T18:09:34:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:34:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:34:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:34:     at Module._compile (module.js:652:30)
2020-09-18T18:09:34:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:34:     at Module.load (module.js:565:32)
2020-09-18T18:09:34:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:34:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:34:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:34:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:34: npm
2020-09-18T18:09:34:  ERR! code ELIFECYCLE
2020-09-18T18:09:34: npm ERR! errno 1
2020-09-18T18:09:34: npm
2020-09-18T18:09:34:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:34: npm ERR! Exit status 1
2020-09-18T18:09:34: npm ERR! 
2020-09-18T18:09:34: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:34: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:36: 
2020-09-18T18:09:36: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:36: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_34_659Z-debug.log
2020-09-18T18:09:41: internal/fs.js:55
2020-09-18T18:09:41:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:41:   ^
2020-09-18T18:09:41: 
2020-09-18T18:09:41: Error: Unknown file open flag: undefined
2020-09-18T18:09:41:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:41:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:41:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:41:     at Module._compile (module.js:652:30)
2020-09-18T18:09:41:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:41:     at Module.load (module.js:565:32)
2020-09-18T18:09:41:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:41:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:41:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:41:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:41: npm
2020-09-18T18:09:41:  ERR! code ELIFECYCLE
2020-09-18T18:09:41: npm ERR! errno 1
2020-09-18T18:09:41: npm
2020-09-18T18:09:41:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:41: npm ERR! Exit status 1
2020-09-18T18:09:41:  
2020-09-18T18:09:41: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:41: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:43: 
2020-09-18T18:09:43: npm
2020-09-18T18:09:43:  ERR! A complete log of this run can be found in:
2020-09-18T18:09:43: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_41_191Z-debug.log
2020-09-18T18:09:47: internal/fs.js:55
2020-09-18T18:09:47:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:47:   ^
2020-09-18T18:09:47: 
2020-09-18T18:09:47: Error: Unknown file open flag: undefined
2020-09-18T18:09:47:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:47:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:47:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:47:     at Module._compile (module.js:652:30)
2020-09-18T18:09:47:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:47:     at Module.load (module.js:565:32)
2020-09-18T18:09:47:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:47:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:47:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:47:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:47: npm
2020-09-18T18:09:47:  ERR! code ELIFECYCLE
2020-09-18T18:09:47: npm ERR! errno 1
2020-09-18T18:09:47: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:47: npm ERR! Exit status 1
2020-09-18T18:09:47: npm ERR! 
2020-09-18T18:09:47: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:47: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:50: 
2020-09-18T18:09:50: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:50: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_47_829Z-debug.log
2020-09-18T18:09:55: internal/fs.js:55
2020-09-18T18:09:55:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:09:55:   ^
2020-09-18T18:09:55: 
2020-09-18T18:09:55: Error: Unknown file open flag: undefined
2020-09-18T18:09:55:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:09:55:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:09:55:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:09:55:     at Module._compile (module.js:652:30)
2020-09-18T18:09:55:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:09:55:     at Module.load (module.js:565:32)
2020-09-18T18:09:55:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:09:55:     at Function.Module._load (module.js:497:3)
2020-09-18T18:09:55:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:09:55:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:09:55: npm
2020-09-18T18:09:55:  ERR! code ELIFECYCLE
2020-09-18T18:09:55: npm ERR!
2020-09-18T18:09:55:  errno 1
2020-09-18T18:09:55: npm
2020-09-18T18:09:55:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:09:55: npm ERR! Exit status 1
2020-09-18T18:09:55:  ERR! 
2020-09-18T18:09:55: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:09:55:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:09:57: 
2020-09-18T18:09:57: npm ERR! A complete log of this run can be found in:
2020-09-18T18:09:57: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_09_55_635Z-debug.log
2020-09-18T18:10:02: internal/fs.js:55
2020-09-18T18:10:02:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:02:   ^
2020-09-18T18:10:02: 
2020-09-18T18:10:02: Error: Unknown file open flag: undefined
2020-09-18T18:10:02:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:02:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:02:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:02:     at Module._compile (module.js:652:30)
2020-09-18T18:10:02:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:02:     at Module.load (module.js:565:32)
2020-09-18T18:10:02:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:02:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:02:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:02:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:02: npm
2020-09-18T18:10:02:  
2020-09-18T18:10:02: ERR!
2020-09-18T18:10:02:  code ELIFECYCLE
2020-09-18T18:10:02: npm 
2020-09-18T18:10:02: ERR! errno 1
2020-09-18T18:10:02: npm
2020-09-18T18:10:02:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:02: npm ERR! Exit status 1
2020-09-18T18:10:02: npm ERR! 
2020-09-18T18:10:02: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:02: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:04: 
2020-09-18T18:10:04: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:04: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_02_587Z-debug.log
2020-09-18T18:10:10: internal/fs.js:55
2020-09-18T18:10:10:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:10:   ^
2020-09-18T18:10:10: 
2020-09-18T18:10:10: Error: Unknown file open flag: undefined
2020-09-18T18:10:10:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:10:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:10:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:10:     at Module._compile (module.js:652:30)
2020-09-18T18:10:10:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:10:     at Module.load (module.js:565:32)
2020-09-18T18:10:10:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:10:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:10:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:10:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:10: npm
2020-09-18T18:10:10:  ERR! code ELIFECYCLE
2020-09-18T18:10:10: ERR! errno 1
2020-09-18T18:10:10: npm
2020-09-18T18:10:10:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:10:  Exit status 1
2020-09-18T18:10:10: npm
2020-09-18T18:10:10:  ERR! 
2020-09-18T18:10:10: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:10: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:12: 
2020-09-18T18:10:12: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:12: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_10_567Z-debug.log
2020-09-18T18:10:15: internal/fs.js:55
2020-09-18T18:10:15:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:15:   ^
2020-09-18T18:10:15: 
2020-09-18T18:10:15: Error: Unknown file open flag: undefined
2020-09-18T18:10:15:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:15:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:15:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:15:     at Module._compile (module.js:652:30)
2020-09-18T18:10:15:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:15:     at Module.load (module.js:565:32)
2020-09-18T18:10:15:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:15:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:15:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:15:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:15: npm
2020-09-18T18:10:15:  ERR! code ELIFECYCLE
2020-09-18T18:10:15: npm ERR! errno 1
2020-09-18T18:10:15: npm
2020-09-18T18:10:15:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:15: npm ERR! Exit status 1
2020-09-18T18:10:15: npm ERR! 
2020-09-18T18:10:15: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:15:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:16: 
2020-09-18T18:10:16: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:16:  ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_15_757Z-debug.log
2020-09-18T18:10:19: internal/fs.js:55
2020-09-18T18:10:19:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:19:   ^
2020-09-18T18:10:19: 
2020-09-18T18:10:19: Error: Unknown file open flag: undefined
2020-09-18T18:10:19:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:19:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:19:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:19:     at Module._compile (module.js:652:30)
2020-09-18T18:10:19:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:19:     at Module.load (module.js:565:32)
2020-09-18T18:10:19:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:19:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:19:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:19:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:19: npm
2020-09-18T18:10:19:  ERR! code ELIFECYCLE
2020-09-18T18:10:19: npm ERR! errno
2020-09-18T18:10:19:  1
2020-09-18T18:10:19: npm
2020-09-18T18:10:19:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:19: npm ERR! Exit status 1
2020-09-18T18:10:19:  ERR! 
2020-09-18T18:10:19: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:19: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:20: 
2020-09-18T18:10:20: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:20: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_19_637Z-debug.log
2020-09-18T18:10:25: internal/fs.js:55
2020-09-18T18:10:25:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:25:   ^
2020-09-18T18:10:25: 
2020-09-18T18:10:25: Error: Unknown file open flag: undefined
2020-09-18T18:10:25:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:25:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:25:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:25:     at Module._compile (module.js:652:30)
2020-09-18T18:10:25:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:25:     at Module.load (module.js:565:32)
2020-09-18T18:10:25:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:25:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:25:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:25:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:25: npm
2020-09-18T18:10:25:  ERR! 
2020-09-18T18:10:25: code ELIFECYCLE
2020-09-18T18:10:25: npm ERR! errno 1
2020-09-18T18:10:25: npm
2020-09-18T18:10:25:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:25: npm ERR! Exit status 1
2020-09-18T18:10:25: npm ERR! 
2020-09-18T18:10:25:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:25: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:27: 
2020-09-18T18:10:27: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:27: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_25_302Z-debug.log
2020-09-18T18:10:31: internal/fs.js:55
2020-09-18T18:10:31:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:31:   ^
2020-09-18T18:10:31: 
2020-09-18T18:10:31: Error: Unknown file open flag: undefined
2020-09-18T18:10:31:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:31:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:31:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:31:     at Module._compile (module.js:652:30)
2020-09-18T18:10:31:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:31:     at Module.load (module.js:565:32)
2020-09-18T18:10:31:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:31:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:31:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:31:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:31: npm
2020-09-18T18:10:31:  
2020-09-18T18:10:31: ERR!
2020-09-18T18:10:31:  code ELIFECYCLE
2020-09-18T18:10:31: npm ERR! errno 1
2020-09-18T18:10:31: npm
2020-09-18T18:10:31:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:31: npm ERR! Exit status 1
2020-09-18T18:10:31: npm ERR! 
2020-09-18T18:10:31: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:31: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:31: 
2020-09-18T18:10:31: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:31: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_31_439Z-debug.log
2020-09-18T18:10:35: internal/fs.js:55
2020-09-18T18:10:35:   throw new Error('Unknown file open flag: ' + flag);
2020-09-18T18:10:35:   ^
2020-09-18T18:10:35: 
2020-09-18T18:10:35: Error: Unknown file open flag: undefined
2020-09-18T18:10:35:     at stringToFlags (internal/fs.js:55:9)
2020-09-18T18:10:35:     at Object.fs.openSync (fs.js:646:51)
2020-09-18T18:10:35:     at Object.<anonymous> (/home/volumio/crawler/index.js:93:13)
2020-09-18T18:10:35:     at Module._compile (module.js:652:30)
2020-09-18T18:10:35:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:10:35:     at Module.load (module.js:565:32)
2020-09-18T18:10:35:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:10:35:     at Function.Module._load (module.js:497:3)
2020-09-18T18:10:35:     at Function.Module.runMain (module.js:693:10)
2020-09-18T18:10:35:     at startup (bootstrap_node.js:188:16)
2020-09-18T18:10:35: npm
2020-09-18T18:10:35:  ERR! code ELIFECYCLE
2020-09-18T18:10:35:  ERR! errno 1
2020-09-18T18:10:35: npm
2020-09-18T18:10:35:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:10:35: npm ERR! Exit status 1
2020-09-18T18:10:35:  ERR! 
2020-09-18T18:10:35: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:10:35: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:10:35: 
2020-09-18T18:10:35: npm ERR! A complete log of this run can be found in:
2020-09-18T18:10:35: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_10_35_748Z-debug.log
2020-09-18T18:12:37: module.js:549
2020-09-18T18:12:37:     throw err;
2020-09-18T18:12:37:     ^
2020-09-18T18:12:37: 
2020-09-18T18:12:37: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:37:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:37:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:37:     at Module.require (module.js:596:17)
2020-09-18T18:12:37:     at require (internal/module.js:11:18)
2020-09-18T18:12:37:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:37:     at Module._compile (module.js:652:30)
2020-09-18T18:12:37:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:37:     at Module.load (module.js:565:32)
2020-09-18T18:12:37:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:37:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:37: npm
2020-09-18T18:12:37:  
2020-09-18T18:12:37: ERR!
2020-09-18T18:12:37:  
2020-09-18T18:12:37: code
2020-09-18T18:12:37:  ELIFECYCLE
2020-09-18T18:12:37: npm 
2020-09-18T18:12:37: ERR!
2020-09-18T18:12:37:  
2020-09-18T18:12:37: errno 1
2020-09-18T18:12:37: npm
2020-09-18T18:12:37:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:37:  ERR!
2020-09-18T18:12:37:  Exit status 1
2020-09-18T18:12:37:  
2020-09-18T18:12:37: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:37:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:37: npm
2020-09-18T18:12:37:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:37: 
2020-09-18T18:12:37: npm ERR! A complete log of this run can be found in:
2020-09-18T18:12:37:  ERR!     /home/volumio/.npm/_logs/2020-09-18T10_12_37_212Z-debug.log
2020-09-18T18:12:41: module.js:549
2020-09-18T18:12:41:     throw err;
2020-09-18T18:12:41:     ^
2020-09-18T18:12:41: 
2020-09-18T18:12:41: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:41:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:41:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:41:     at Module.require (module.js:596:17)
2020-09-18T18:12:41:     at require (internal/module.js:11:18)
2020-09-18T18:12:41:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:41:     at Module._compile (module.js:652:30)
2020-09-18T18:12:41:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:41:     at Module.load (module.js:565:32)
2020-09-18T18:12:41:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:41:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:41: npm
2020-09-18T18:12:41:  ERR! code ELIFECYCLE
2020-09-18T18:12:41: npm ERR! errno 1
2020-09-18T18:12:41: npm
2020-09-18T18:12:41:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:41: npm ERR! Exit status 1
2020-09-18T18:12:41: npm ERR! 
2020-09-18T18:12:41: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:41: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:41: npm
2020-09-18T18:12:41:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:41: 
2020-09-18T18:12:41: npm ERR! A complete log of this run can be found in:
2020-09-18T18:12:41: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_12_41_189Z-debug.log
2020-09-18T18:12:45: module.js:549
2020-09-18T18:12:45:     throw err;
2020-09-18T18:12:45:     ^
2020-09-18T18:12:45: 
2020-09-18T18:12:45: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:45:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:45:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:45:     at Module.require (module.js:596:17)
2020-09-18T18:12:45:     at require (internal/module.js:11:18)
2020-09-18T18:12:45:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:45:     at Module._compile (module.js:652:30)
2020-09-18T18:12:45:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:45:     at Module.load (module.js:565:32)
2020-09-18T18:12:45:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:45:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:45: npm
2020-09-18T18:12:45:  
2020-09-18T18:12:45: ERR!
2020-09-18T18:12:45:  
2020-09-18T18:12:45: code
2020-09-18T18:12:45:  ELIFECYCLE
2020-09-18T18:12:45: npm
2020-09-18T18:12:45:  ERR! errno 1
2020-09-18T18:12:45: npm
2020-09-18T18:12:45:  
2020-09-18T18:12:45: ERR!
2020-09-18T18:12:45:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:45: npm ERR! Exit status 1
2020-09-18T18:12:45: npm ERR! 
2020-09-18T18:12:45: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:45: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:45: npm
2020-09-18T18:12:45:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:45: 
2020-09-18T18:12:45: npm ERR! A complete log of this run can be found in:
2020-09-18T18:12:45: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_12_45_180Z-debug.log
2020-09-18T18:12:50: module.js:549
2020-09-18T18:12:50:     throw err;
2020-09-18T18:12:50:     ^
2020-09-18T18:12:50: 
2020-09-18T18:12:50: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:50:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:50:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:50:     at Module.require (module.js:596:17)
2020-09-18T18:12:50:     at require (internal/module.js:11:18)
2020-09-18T18:12:50:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:50:     at Module._compile (module.js:652:30)
2020-09-18T18:12:50:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:50:     at Module.load (module.js:565:32)
2020-09-18T18:12:50:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:50:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:50: npm
2020-09-18T18:12:50:  
2020-09-18T18:12:50: ERR!
2020-09-18T18:12:50:  
2020-09-18T18:12:50: code
2020-09-18T18:12:50:  ELIFECYCLE
2020-09-18T18:12:50: npm
2020-09-18T18:12:50:  ERR! errno 1
2020-09-18T18:12:50: npm
2020-09-18T18:12:50:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:50: npm ERR! Exit status 1
2020-09-18T18:12:50: npm ERR! 
2020-09-18T18:12:50:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:50: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:50: npm
2020-09-18T18:12:50:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:50: 
2020-09-18T18:12:50:  A complete log of this run can be found in:
2020-09-18T18:12:50: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_12_50_204Z-debug.log
2020-09-18T18:12:53: module.js:549
2020-09-18T18:12:53:     throw err;
2020-09-18T18:12:53:     ^
2020-09-18T18:12:53: 
2020-09-18T18:12:53: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:53:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:53:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:53:     at Module.require (module.js:596:17)
2020-09-18T18:12:53:     at require (internal/module.js:11:18)
2020-09-18T18:12:53:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:53:     at Module._compile (module.js:652:30)
2020-09-18T18:12:53:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:53:     at Module.load (module.js:565:32)
2020-09-18T18:12:53:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:53:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:53: npm
2020-09-18T18:12:53:  ERR! code ELIFECYCLE
2020-09-18T18:12:53:  ERR! errno 1
2020-09-18T18:12:53: npm
2020-09-18T18:12:53:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:53: npm ERR! Exit status 1
2020-09-18T18:12:53: npm ERR! 
2020-09-18T18:12:53:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:53: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:53: npm
2020-09-18T18:12:53:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:54: 
2020-09-18T18:12:54: npm ERR! A complete log of this run can be found in:
2020-09-18T18:12:54: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_12_53_721Z-debug.log
2020-09-18T18:12:58: module.js:549
2020-09-18T18:12:58:     throw err;
2020-09-18T18:12:58:     ^
2020-09-18T18:12:58: 
2020-09-18T18:12:58: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:12:58:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:12:58:     at Function.Module._load (module.js:474:25)
2020-09-18T18:12:58:     at Module.require (module.js:596:17)
2020-09-18T18:12:58:     at require (internal/module.js:11:18)
2020-09-18T18:12:58:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:12:58:     at Module._compile (module.js:652:30)
2020-09-18T18:12:58:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:12:58:     at Module.load (module.js:565:32)
2020-09-18T18:12:58:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:12:58:     at Function.Module._load (module.js:497:3)
2020-09-18T18:12:58: npm
2020-09-18T18:12:58:  ERR! code ELIFECYCLE
2020-09-18T18:12:58: npm
2020-09-18T18:12:58:  ERR! errno
2020-09-18T18:12:58:  1
2020-09-18T18:12:58: npm
2020-09-18T18:12:58:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:12:58: npm ERR! Exit status 1
2020-09-18T18:12:58: npm ERR! 
2020-09-18T18:12:58: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:12:58: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:12:58: npm
2020-09-18T18:12:58:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:12:58: 
2020-09-18T18:12:58: npm ERR! A complete log of this run can be found in:
2020-09-18T18:12:58:      /home/volumio/.npm/_logs/2020-09-18T10_12_58_235Z-debug.log
2020-09-18T18:13:03: module.js:549
2020-09-18T18:13:03:     throw err;
2020-09-18T18:13:03:     ^
2020-09-18T18:13:03: 
2020-09-18T18:13:03: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:03:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:03:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:03:     at Module.require (module.js:596:17)
2020-09-18T18:13:03:     at require (internal/module.js:11:18)
2020-09-18T18:13:03:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:03:     at Module._compile (module.js:652:30)
2020-09-18T18:13:03:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:03:     at Module.load (module.js:565:32)
2020-09-18T18:13:03:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:03:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:03: npm
2020-09-18T18:13:03:  ERR! code ELIFECYCLE
2020-09-18T18:13:03:  ERR! errno 1
2020-09-18T18:13:03: npm
2020-09-18T18:13:03:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:03: npm ERR! Exit status 1
2020-09-18T18:13:03:  ERR! 
2020-09-18T18:13:03: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:03: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:03: npm
2020-09-18T18:13:03:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:06: 
2020-09-18T18:13:06: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:06:      /home/volumio/.npm/_logs/2020-09-18T10_13_03_096Z-debug.log
2020-09-18T18:13:10: module.js:549
2020-09-18T18:13:10:     throw err;
2020-09-18T18:13:10:     ^
2020-09-18T18:13:10: 
2020-09-18T18:13:10: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:10:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:10:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:10:     at Module.require (module.js:596:17)
2020-09-18T18:13:10:     at require (internal/module.js:11:18)
2020-09-18T18:13:10:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:10:     at Module._compile (module.js:652:30)
2020-09-18T18:13:10:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:10:     at Module.load (module.js:565:32)
2020-09-18T18:13:10:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:10:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:10: npm
2020-09-18T18:13:10:  ERR! code ELIFECYCLE
2020-09-18T18:13:10: npm ERR!
2020-09-18T18:13:10:  errno 1
2020-09-18T18:13:10: npm
2020-09-18T18:13:10:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:10:  Exit status 1
2020-09-18T18:13:10: npm ERR! 
2020-09-18T18:13:10:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:10: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:10: npm
2020-09-18T18:13:10:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:10: 
2020-09-18T18:13:10: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:10: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_10_235Z-debug.log
2020-09-18T18:13:14: module.js:549
2020-09-18T18:13:14:     throw err;
2020-09-18T18:13:14:     ^
2020-09-18T18:13:14: 
2020-09-18T18:13:14: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:14:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:14:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:14:     at Module.require (module.js:596:17)
2020-09-18T18:13:14:     at require (internal/module.js:11:18)
2020-09-18T18:13:14:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:14:     at Module._compile (module.js:652:30)
2020-09-18T18:13:14:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:14:     at Module.load (module.js:565:32)
2020-09-18T18:13:14:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:14:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:14: npm
2020-09-18T18:13:14:  ERR! code ELIFECYCLE
2020-09-18T18:13:14: npm ERR! errno 1
2020-09-18T18:13:14: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:14: npm ERR! Exit status 1
2020-09-18T18:13:14: npm ERR! 
2020-09-18T18:13:14: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:14: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:14: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:17: 
2020-09-18T18:13:17: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:17: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_14_609Z-debug.log
2020-09-18T18:13:21: module.js:549
2020-09-18T18:13:21:     throw err;
2020-09-18T18:13:21:     ^
2020-09-18T18:13:21: 
2020-09-18T18:13:21: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:21:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:21:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:21:     at Module.require (module.js:596:17)
2020-09-18T18:13:21:     at require (internal/module.js:11:18)
2020-09-18T18:13:21:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:21:     at Module._compile (module.js:652:30)
2020-09-18T18:13:21:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:21:     at Module.load (module.js:565:32)
2020-09-18T18:13:21:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:21:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:21: npm
2020-09-18T18:13:21:  ERR! code
2020-09-18T18:13:21:  ELIFECYCLE
2020-09-18T18:13:21: npm
2020-09-18T18:13:21:  ERR! errno 1
2020-09-18T18:13:21: npm
2020-09-18T18:13:21:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:21:  Exit status 1
2020-09-18T18:13:21: npm
2020-09-18T18:13:21:  ERR! 
2020-09-18T18:13:21: ERR!
2020-09-18T18:13:21:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:21:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:21: npm
2020-09-18T18:13:21:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:24: 
2020-09-18T18:13:24: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:24: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_21_838Z-debug.log
2020-09-18T18:13:28: module.js:549
2020-09-18T18:13:28:     throw err;
2020-09-18T18:13:28:     ^
2020-09-18T18:13:28: 
2020-09-18T18:13:28: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:28:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:28:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:28:     at Module.require (module.js:596:17)
2020-09-18T18:13:28:     at require (internal/module.js:11:18)
2020-09-18T18:13:28:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:28:     at Module._compile (module.js:652:30)
2020-09-18T18:13:28:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:28:     at Module.load (module.js:565:32)
2020-09-18T18:13:28:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:28:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:28: npm
2020-09-18T18:13:28:  ERR! code ELIFECYCLE
2020-09-18T18:13:28: errno 1
2020-09-18T18:13:28: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:28: npm ERR! Exit status 1
2020-09-18T18:13:28: npm ERR! 
2020-09-18T18:13:28: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:28: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:28: npm
2020-09-18T18:13:28:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:29: 
2020-09-18T18:13:29: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:29: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_28_949Z-debug.log
2020-09-18T18:13:32: module.js:549
2020-09-18T18:13:32:     throw err;
2020-09-18T18:13:32:     ^
2020-09-18T18:13:32: 
2020-09-18T18:13:32: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:32:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:32:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:32:     at Module.require (module.js:596:17)
2020-09-18T18:13:32:     at require (internal/module.js:11:18)
2020-09-18T18:13:32:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:32:     at Module._compile (module.js:652:30)
2020-09-18T18:13:32:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:32:     at Module.load (module.js:565:32)
2020-09-18T18:13:32:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:32:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:32: npm
2020-09-18T18:13:32:  ERR! code ELIFECYCLE
2020-09-18T18:13:32: npm ERR! errno
2020-09-18T18:13:32:  1
2020-09-18T18:13:32: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:32: npm ERR! Exit status 1
2020-09-18T18:13:32: npm ERR! 
2020-09-18T18:13:32: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:32: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:32: npm
2020-09-18T18:13:32:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:33: 
2020-09-18T18:13:33: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:33: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_32_125Z-debug.log
2020-09-18T18:13:37: module.js:549
2020-09-18T18:13:37:     throw err;
2020-09-18T18:13:37:     ^
2020-09-18T18:13:37: 
2020-09-18T18:13:37: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:37:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:37:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:37:     at Module.require (module.js:596:17)
2020-09-18T18:13:37:     at require (internal/module.js:11:18)
2020-09-18T18:13:37:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:37:     at Module._compile (module.js:652:30)
2020-09-18T18:13:37:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:37:     at Module.load (module.js:565:32)
2020-09-18T18:13:37:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:37:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:37: npm
2020-09-18T18:13:37:  ERR! code ELIFECYCLE
2020-09-18T18:13:37: npm ERR! errno 1
2020-09-18T18:13:37: npm
2020-09-18T18:13:37:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:37: npm ERR! Exit status 1
2020-09-18T18:13:37: npm ERR! 
2020-09-18T18:13:37: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:37: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:37: npm
2020-09-18T18:13:37:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:37: 
2020-09-18T18:13:37: ERR! A complete log of this run can be found in:
2020-09-18T18:13:37: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_37_553Z-debug.log
2020-09-18T18:13:40: module.js:549
2020-09-18T18:13:40:     throw err;
2020-09-18T18:13:40:     ^
2020-09-18T18:13:40: 
2020-09-18T18:13:40: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:40:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:40:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:40:     at Module.require (module.js:596:17)
2020-09-18T18:13:40:     at require (internal/module.js:11:18)
2020-09-18T18:13:40:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:40:     at Module._compile (module.js:652:30)
2020-09-18T18:13:40:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:40:     at Module.load (module.js:565:32)
2020-09-18T18:13:40:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:40:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:40: npm
2020-09-18T18:13:40:  ERR! code ELIFECYCLE
2020-09-18T18:13:40:  1
2020-09-18T18:13:40: npm
2020-09-18T18:13:40:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:40: npm ERR! Exit status 1
2020-09-18T18:13:40: npm ERR! 
2020-09-18T18:13:40: ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:40: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:40: npm
2020-09-18T18:13:40:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:41: 
2020-09-18T18:13:41: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:41: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_40_748Z-debug.log
2020-09-18T18:13:46: module.js:549
2020-09-18T18:13:46:     throw err;
2020-09-18T18:13:46:     ^
2020-09-18T18:13:46: 
2020-09-18T18:13:46: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:46:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:46:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:46:     at Module.require (module.js:596:17)
2020-09-18T18:13:46:     at require (internal/module.js:11:18)
2020-09-18T18:13:46:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:46:     at Module._compile (module.js:652:30)
2020-09-18T18:13:46:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:46:     at Module.load (module.js:565:32)
2020-09-18T18:13:46:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:46:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:46: npm
2020-09-18T18:13:46:  
2020-09-18T18:13:46: ERR!
2020-09-18T18:13:46:  
2020-09-18T18:13:46: code
2020-09-18T18:13:46:  ELIFECYCLE
2020-09-18T18:13:46: npm ERR! errno 1
2020-09-18T18:13:46: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:46: npm ERR! Exit status 1
2020-09-18T18:13:46: npm ERR! 
2020-09-18T18:13:46: npm
2020-09-18T18:13:46:  
2020-09-18T18:13:46: ERR!
2020-09-18T18:13:46:  Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:46: npm
2020-09-18T18:13:46:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:46: npm
2020-09-18T18:13:46:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:46: 
2020-09-18T18:13:46: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:46: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_46_137Z-debug.log
2020-09-18T18:13:49: module.js:549
2020-09-18T18:13:49:     throw err;
2020-09-18T18:13:49:     ^
2020-09-18T18:13:49: 
2020-09-18T18:13:49: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:49:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:49:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:49:     at Module.require (module.js:596:17)
2020-09-18T18:13:49:     at require (internal/module.js:11:18)
2020-09-18T18:13:49:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:49:     at Module._compile (module.js:652:30)
2020-09-18T18:13:49:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:49:     at Module.load (module.js:565:32)
2020-09-18T18:13:49:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:49:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:50: npm
2020-09-18T18:13:50:  ERR! code ELIFECYCLE
2020-09-18T18:13:50: npm ERR! errno 1
2020-09-18T18:13:50: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:50: npm ERR! Exit status 1
2020-09-18T18:13:50: npm ERR! 
2020-09-18T18:13:50: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:50: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:50: npm
2020-09-18T18:13:50:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:50: 
2020-09-18T18:13:50: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:50: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_13_50_025Z-debug.log
2020-09-18T18:13:54: module.js:549
2020-09-18T18:13:54:     throw err;
2020-09-18T18:13:54:     ^
2020-09-18T18:13:54: 
2020-09-18T18:13:54: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:13:54:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:13:54:     at Function.Module._load (module.js:474:25)
2020-09-18T18:13:54:     at Module.require (module.js:596:17)
2020-09-18T18:13:54:     at require (internal/module.js:11:18)
2020-09-18T18:13:54:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:13:54:     at Module._compile (module.js:652:30)
2020-09-18T18:13:54:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:13:54:     at Module.load (module.js:565:32)
2020-09-18T18:13:54:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:13:54:     at Function.Module._load (module.js:497:3)
2020-09-18T18:13:54: npm
2020-09-18T18:13:54:  
2020-09-18T18:13:54: ERR!
2020-09-18T18:13:54:  
2020-09-18T18:13:54: code
2020-09-18T18:13:54:  ELIFECYCLE
2020-09-18T18:13:54: npm
2020-09-18T18:13:54:  
2020-09-18T18:13:54: ERR!
2020-09-18T18:13:54:  errno 1
2020-09-18T18:13:54: npm
2020-09-18T18:13:54:  
2020-09-18T18:13:54: ERR!
2020-09-18T18:13:54:  wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:13:54: npm ERR! Exit status 1
2020-09-18T18:13:54: npm ERR! 
2020-09-18T18:13:54: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:13:54: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:13:54: npm
2020-09-18T18:13:54:  
2020-09-18T18:13:54: WARN
2020-09-18T18:13:54:  Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:13:57: 
2020-09-18T18:13:57: npm ERR! A complete log of this run can be found in:
2020-09-18T18:13:57: ERR!
2020-09-18T18:13:57:      /home/volumio/.npm/_logs/2020-09-18T10_13_54_574Z-debug.log
2020-09-18T18:14:00: module.js:549
2020-09-18T18:14:00:     throw err;
2020-09-18T18:14:00:     ^
2020-09-18T18:14:00: 
2020-09-18T18:14:00: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:00:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:00:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:00:     at Module.require (module.js:596:17)
2020-09-18T18:14:00:     at require (internal/module.js:11:18)
2020-09-18T18:14:00:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:00:     at Module._compile (module.js:652:30)
2020-09-18T18:14:00:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:00:     at Module.load (module.js:565:32)
2020-09-18T18:14:00:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:00:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:00: npm
2020-09-18T18:14:00:  ERR! code ELIFECYCLE
2020-09-18T18:14:00:  errno 1
2020-09-18T18:14:00: npm
2020-09-18T18:14:00:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:00: npm ERR! Exit status 1
2020-09-18T18:14:00: npm ERR! 
2020-09-18T18:14:00:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:00: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:00: npm
2020-09-18T18:14:00:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:14:01: 
2020-09-18T18:14:01: npm ERR! A complete log of this run can be found in:
2020-09-18T18:14:01: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_14_00_431Z-debug.log
2020-09-18T18:14:04: module.js:549
2020-09-18T18:14:04:     throw err;
2020-09-18T18:14:04:     ^
2020-09-18T18:14:04: 
2020-09-18T18:14:04: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:04:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:04:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:04:     at Module.require (module.js:596:17)
2020-09-18T18:14:04:     at require (internal/module.js:11:18)
2020-09-18T18:14:04:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:04:     at Module._compile (module.js:652:30)
2020-09-18T18:14:04:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:04:     at Module.load (module.js:565:32)
2020-09-18T18:14:04:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:04:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:04: npm
2020-09-18T18:14:04:  ERR! code ELIFECYCLE
2020-09-18T18:14:04:  errno 1
2020-09-18T18:14:04: npm
2020-09-18T18:14:04:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:04: npm ERR! Exit status 1
2020-09-18T18:14:04: npm ERR! 
2020-09-18T18:14:04:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:04: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:04: npm
2020-09-18T18:14:04:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:14:05: 
2020-09-18T18:14:05: npm ERR!
2020-09-18T18:14:05:  A complete log of this run can be found in:
2020-09-18T18:14:05: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_14_04_683Z-debug.log
2020-09-18T18:14:09: module.js:549
2020-09-18T18:14:09:     throw err;
2020-09-18T18:14:09:     ^
2020-09-18T18:14:09: 
2020-09-18T18:14:09: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:09:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:09:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:09:     at Module.require (module.js:596:17)
2020-09-18T18:14:09:     at require (internal/module.js:11:18)
2020-09-18T18:14:09:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:09:     at Module._compile (module.js:652:30)
2020-09-18T18:14:09:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:09:     at Module.load (module.js:565:32)
2020-09-18T18:14:09:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:09:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:09: npm
2020-09-18T18:14:09:  ERR! code ELIFECYCLE
2020-09-18T18:14:09: npm ERR! errno 1
2020-09-18T18:14:09: npm
2020-09-18T18:14:09:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:09: npm ERR! Exit status 1
2020-09-18T18:14:09: npm ERR! 
2020-09-18T18:14:09: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:09: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:09: npm
2020-09-18T18:14:09:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:14:09: 
2020-09-18T18:14:09: npm ERR! A complete log of this run can be found in:
2020-09-18T18:14:09: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_14_09_569Z-debug.log
2020-09-18T18:14:14: module.js:549
2020-09-18T18:14:14:     throw err;
2020-09-18T18:14:14:     ^
2020-09-18T18:14:14: 
2020-09-18T18:14:14: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:14:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:14:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:14:     at Module.require (module.js:596:17)
2020-09-18T18:14:14:     at require (internal/module.js:11:18)
2020-09-18T18:14:14:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:14:     at Module._compile (module.js:652:30)
2020-09-18T18:14:14:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:14:     at Module.load (module.js:565:32)
2020-09-18T18:14:14:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:14:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:14: npm ERR! code ELIFECYCLE
2020-09-18T18:14:14: npm ERR! errno 1
2020-09-18T18:14:14: npm ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:14: npm ERR! Exit status 1
2020-09-18T18:14:14: npm ERR! 
2020-09-18T18:14:14: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:14:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:14: npm WARN
2020-09-18T18:14:14:  Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:14:14: 
2020-09-18T18:14:14: npm ERR! A complete log of this run can be found in:
2020-09-18T18:14:14:      /home/volumio/.npm/_logs/2020-09-18T10_14_14_201Z-debug.log
2020-09-18T18:14:18: module.js:549
2020-09-18T18:14:18:     throw err;
2020-09-18T18:14:18:     ^
2020-09-18T18:14:18: 
2020-09-18T18:14:18: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:18:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:18:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:18:     at Module.require (module.js:596:17)
2020-09-18T18:14:18:     at require (internal/module.js:11:18)
2020-09-18T18:14:18:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:18:     at Module._compile (module.js:652:30)
2020-09-18T18:14:18:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:18:     at Module.load (module.js:565:32)
2020-09-18T18:14:18:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:18:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:18: npm
2020-09-18T18:14:18:  ERR! code ELIFECYCLE
2020-09-18T18:14:18:  1
2020-09-18T18:14:18: npm
2020-09-18T18:14:18:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:18: npm ERR! Exit status 1
2020-09-18T18:14:18: npm ERR! 
2020-09-18T18:14:18:  ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:18: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:18: npm
2020-09-18T18:14:18:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:14:21: 
2020-09-18T18:14:21: npm ERR! A complete log of this run can be found in:
2020-09-18T18:14:21: npm ERR!     /home/volumio/.npm/_logs/2020-09-18T10_14_18_407Z-debug.log
2020-09-18T18:14:25: module.js:549
2020-09-18T18:14:25:     throw err;
2020-09-18T18:14:25:     ^
2020-09-18T18:14:25: 
2020-09-18T18:14:25: Error: Cannot find module 'github-webhook-handler'
2020-09-18T18:14:25:     at Function.Module._resolveFilename (module.js:547:15)
2020-09-18T18:14:25:     at Function.Module._load (module.js:474:25)
2020-09-18T18:14:25:     at Module.require (module.js:596:17)
2020-09-18T18:14:25:     at require (internal/module.js:11:18)
2020-09-18T18:14:25:     at Object.<anonymous> (/home/volumio/crawler/index.js:2:23)
2020-09-18T18:14:25:     at Module._compile (module.js:652:30)
2020-09-18T18:14:25:     at Object.Module._extensions..js (module.js:663:10)
2020-09-18T18:14:25:     at Module.load (module.js:565:32)
2020-09-18T18:14:25:     at tryModuleLoad (module.js:505:12)
2020-09-18T18:14:25:     at Function.Module._load (module.js:497:3)
2020-09-18T18:14:25: npm
2020-09-18T18:14:25:  ERR! code ELIFECYCLE
2020-09-18T18:14:25: npm
2020-09-18T18:14:25:  ERR! errno 1
2020-09-18T18:14:25: npm
2020-09-18T18:14:25:  ERR! wells-web-crawler@1.0.0 ci: `WEBHOOK_SECRET=wells-crawler node ./index.js`
2020-09-18T18:14:25:  Exit status 1
2020-09-18T18:14:25: npm
2020-09-18T18:14:25:  ERR!
2020-09-18T18:14:25:  
2020-09-18T18:14:25: npm ERR! Failed at the wells-web-crawler@1.0.0 ci script.
2020-09-18T18:14:25:  ERR!
2020-09-18T18:14:25:  This is probably not a problem with npm. There is likely additional logging output above.
2020-09-18T18:14:25: npm
2020-09-18T18:14:25:  WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-09-18T18:23:47: Already on 'master'
2020-09-18T18:23:49: From https://github.com/shiehnpin/crawler
2020-09-18T18:23:49:    72aa881..9c8ac8f  master     -> origin/master
2020-09-18T18:23:57: npm
2020-09-18T18:23:57:  
2020-09-18T18:23:57: WARN wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:23:57: 
2020-09-18T18:24:07: 
2020-09-18T18:24:07:   error: missing required argument `id|name|namespace|all'
2020-09-18T18:24:07: 
2020-09-18T18:28:03: Already on 'master'
2020-09-18T18:28:05: From https://github.com/shiehnpin/crawler
2020-09-18T18:28:05:    9c8ac8f..dcafa66  master     -> origin/master
2020-09-18T18:28:13: npm
2020-09-18T18:28:13:  
2020-09-18T18:28:13: WARN
2020-09-18T18:28:13:  wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:28:13: 
2020-09-18T18:28:24: 
2020-09-18T18:28:24:   error: missing required argument `id|name|namespace|all'
2020-09-18T18:28:24: 
2020-09-18T18:35:56: Already on 'master'
2020-09-18T18:35:58: From https://github.com/shiehnpin/crawler
2020-09-18T18:35:58:    dcafa66..03961e7  master     -> origin/master
2020-09-18T18:36:06: npm
2020-09-18T18:36:06:  
2020-09-18T18:36:06: WARN
2020-09-18T18:36:06:  wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:36:06: 
2020-09-18T18:36:17: 
2020-09-18T18:36:17:   error: missing required argument `id|name|namespace|all'
2020-09-18T18:36:17: 
2020-09-18T18:40:07: Already on 'master'
2020-09-18T18:40:09: From https://github.com/shiehnpin/crawler
2020-09-18T18:40:09:    03961e7..757a4ec  master     -> origin/master
2020-09-18T18:40:17: npm
2020-09-18T18:40:17:  WARN wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:40:17: 
2020-09-18T18:43:51: Already on 'master'
2020-09-18T18:44:01: From https://github.com/shiehnpin/crawler
2020-09-18T18:44:01:    757a4ec..60271f2  master     -> origin/master
2020-09-18T18:44:10: npm
2020-09-18T18:44:10:  WARN wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:44:10: 
2020-09-18T18:48:01: Already on 'master'
2020-09-18T18:48:03: From https://github.com/shiehnpin/crawler
2020-09-18T18:48:03:    60271f2..08ecb01  master     -> origin/master
2020-09-18T18:48:11: npm
2020-09-18T18:48:11:  
2020-09-18T18:48:11: WARN wells-web-crawler@1.0.0 No repository field.
2020-09-18T18:48:11: 
2020-09-18T18:48:42: [PM2][ERROR] Reload already in progress, please try again in 8 seconds or use --force
2020-09-19T14:08:28: Already on 'master'
2020-09-19T14:08:30: From https://github.com/shiehnpin/crawler
2020-09-19T14:08:30:    08ecb01..2835405  master     -> origin/master
2020-09-19T14:08:41: npm
2020-09-19T14:08:41:  WARN wells-web-crawler@1.0.0 No repository field.
2020-09-19T14:08:41: 
